### ISSUE TITLE
 BIOMOD_Modeling error

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#109]
HI,biomod2 team：
   Is there a problem that the model cannot run？
![image](https://user-images.githubusercontent.com/104480028/192984083-92e37f38-dd2d-466a-aa4c-b9953262d407.png)
![image](https://user-images.githubusercontent.com/104480028/192984251-96882dc3-f662-46d8-8447-eeb47e043cec.png)
yours，chen

**Comment by rpatin** [comment]
Hello Chen,
Thank you for reporting.
Individual models may fail for numerous reasons, often specific to each method (FDA, Maxent, etc...). For instance, it can happen because you have a limited amount of data or lack of contrast in environmental data. There may also be some random components in the different methods so if you re-run `BIOMOD_Modeling` you may see that some models that previously failed now work properly. It can help you identify whether it is a general problem (all methods are affected), which then probably stems from your data (presence/absence, environmental data, extent, resolution) or a problem specific to a few methods, in which case it requires a deeper understanding of each methods to be able to solve it.
If you want more details, we would require a bit more information about your data (summary of presence/absence, environmental data, extent, resolution, choice of pseudo-absences).
Cheers,
Rémi
