### ISSUE TITLE
Continuing the same biomod2 model?

### ISSUE THREAD

**Issue by ingridgarfeltpaulsen** [biomodhub/biomod2#117]
Dear biomod2 users,

I am running the biomod2 models on GPS data from reindeer. The models involve 6 models with 10 runs each + full models (n=77). Unfortunately, the biomod2 model crashed after 4 days of running and I can see from the items in the folder that 75 out of 77 model runs were successful. Is there any way to continue running the same model so I don’t have to start all over again?

Thank you!

**Comment by MayaGueguen** [comment]
Hello Ingrid,

Thank you for reporting :pray: 
I'd just like to ask a few precisions to be sure I understood the situation : 

- you set your modeling set with 6 models x 10 runs + full models, leading to 77 single models to be computed
- you ran the `BIOMOD_Modeling` function, but you got "only" 75 out of 77 of your single models wanted
- **the information I'm not sure about is** : do you have a `models.out` object created within your simulation folder or not ?

If yes, it means that the function went through, and that 2 models failed due to data / selection of calibration lines / other reason.
If no, it means your computer / r session crashed before the end of the function, so it did not created the full `models.out` output.

In the 1st case, you're okay to get along for example with projections or ensemble modeling, even if 2 single models failed.
In the 2nd case, unfortunately, without the `models.out` object, we will not be able to pursue your simulation analysis....
And in both case, it it not possible to restart a `BIOMOD_Modeling` simulation phase to fill gaps or missing models (_it would imply too many checks and tests to see what's already there, what was used, what failed or not..._).

Sorry for the bad news if you have to re-run everything :disappointed: 
I hope it helps, and you'll manage to complete your modelisation.
Maya

**Comment by ingridgarfeltpaulsen** [comment]
Hi Maya,

Thank you for yor reply. The models.out object was unfortunately not
created so it sounds like I have to start the model again ! Just wanted to
make sure there was absolutely nothing I could do before restarting the
analyses.

(Sidenote woopsy: I meant 7 models with 11 evaluation repetitions (10
runs + 1 full) = 77 single models. Excuse my math 😋)

All the best,
Ingrid
