### ISSUE TITLE
MARS fails to project when using categorical variables

### ISSUE THREAD

**Issue by mjwestgate** [biomodhub/biomod2#119]
Hello `biomod2` team! Great work on the new release, it's a fantastic piece of work. I was testing categorical variables with MARS today and received this error:
```
Projecting Koala_PA1_Full_MARS ...Error in { : task 1 failed - "cannot use this function"
```
Delving into the code a bit, it actually errors at [line 292](https://github.com/biomodhub/biomod2/blob/a57489e95fe245552daf4dc2e8690260a71f3993/R/BIOMOD_Projection.R#L292) in `BIOMOD_Projection.R`, i.e.:
```
      pred.tmp <- predict(mod, new.env, on_0_1000 = on_0_1000, filename = filename
                          , omit.na = omit.na, split.proj = 1
                          , temp_workdir = temp_workdir, seedval = seed.val)
```
When this is run, the error is slightly more informative, but not much:
```
Error in .calcTest(x[1:5], fun, na.rm, forcefun, forceapply) : 
  cannot use this function
```
I'm not sure what this function is calling or what has changed with MARS lately, but thought I'd tag it here in case it affects other users.

**Comment by rpatin** [comment]
Hello Martin,
Thank you for reporting :pray:
Categorical variables are still a bit of a mess. Note that in the near future we will be migrating to `terra` instead of `raster` which should likely improve categorical variables management.
On my end, and with the current version, projection with categorical variables and `MARS` are working. Could you then provide a bit more details on your issue ? Ideally a reproducible example or at least information on the data you are projecting on: is it a raster or a data.frame ?
Rémi
