### ISSUE TITLE
How to combine gis and r to analysis BiomodRangeSize？

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#130]
Hello,biomod2  team：

I encountered some problems about biomod2 visualization. I want to map through arcgis. I use this code to export the 2030 current changes to tif format, and then re classify them. But if so, I will not be able to display stable0.
_**The code in r is as follows.**_
```
myBiomodRangeSize_EM_ssp126_2030 <- BIOMOD_RangeSize(proj.current = CurrentProj_EM, proj.future = ### FutureProj_EMssp126_2030)
myBiomodRangeSize_EM_ssp126_2030
write.csv(myBiomodRangeSize_EM_ssp126_2030$Compt,file = "./myBiomodRangeSize_ssp126_2030.csv")
writeRaster(myBiomodRangeSize_EM_ssp126_2030$Diff.By.Pixel,file = "./myBiomodRangeSize_EM_ssp126_2030.tif",overwrite=T)
```

## Basic plot changing colors and labels
```
plot(myBiomodRangeSize_EM_ssp126_2030$Diff.By.Pixel
     , col = c("brown", "goldenrod1", "grey", "chartreuse3")
     , legend.width = 1, legend.shrink = 0.75
     , axis.args = list(at = seq(-2, 1, 1), labels = c("Loss", "Stable1", "Stable0", "Gain")))
```
![image](https://user-images.githubusercontent.com/104480028/201339554-9f937af8-23c5-496c-99e4-a6907a99a7b5.png)

And I'm not sure if I can understand this？-2 represented “loss” ，-1 represented “Stable1”，0 represented "Stable0"，1 represented "Gain"？If so, How can I change the range of - 1691-630 to - 2 to 1？

The files in tif format are as follows
![image](https://user-images.githubusercontent.com/104480028/201339646-a1ed9751-18cf-4def-87c3-84fd63faddec.png)

I want to ask if there is a good way to input r code into aicgis.

Thank you very much！！

cheers，CHEN

**Comment by chenyongpeng1** [comment]
HI,Biomod2 team:
    Sorry to interrupt to you ! Why the grd file from biomod2 cannot be opened in Arcmap？Others grds can do well!

**Comment by chenyongpeng1** [comment]
Yeah，I have solve it，but I find a new probloem about the results from different platform（R and ArcGIS).
I used WriteRaster function，and transform the Diff.By.Pixel to a GEOTIFF.
But they have different result.
In ArcGIS, I choose the natural segment reclassification command, which is divided into four segments. The generated graph is roughly the same as R's. Unfortunately, when I open the attribute table, the values in LOSS, STABLE1, STABLE0, LOSS and R differ greatly. I don't know where the problem is. How are these values classified in R?
![image](https://user-images.githubusercontent.com/104480028/201899882-2987b2b8-b02b-4e12-a291-4c2797bb6618.png)
![image](https://user-images.githubusercontent.com/104480028/201900100-647faf9a-859d-4fde-86c8-65a125b2edc2.png)

**Comment by chenyongpeng1** [comment]
hello，biomod team：
   I realized that my integration model is a continuous variable with a range of [50-600], rather than the classified - 2, - 2, 0, 1. Therefore, the number of pixels I calculated is incorrect. I want to ask how I should modify my integration model into categories?

```
# Model ensemble models
myBiomodEM <- BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                      models.chosen = 'all
                                      em.by = 'all',
                                      metric.select = c('TSS'),
                                      metric.select.thresh = c(0.7),
                                      var.import = 3,
                                      metric.eval = c('TSS', 'ROC'),
                                      prob.mean = TRUE,
                                      prob.median = TRUE,
                                      prob.cv = TRUE,
                                      prob.ci = TRUE,
                                      prob.ci.alpha = 0.05,
                                      committee.averaging = TRUE,
                                      prob.mean.weight = TRUE,
                                      prob.mean.weight.decay = 'proportional')

```

looking forward to your reply!

**Comment by MayaGueguen** [comment]
Hello Chen,

I think you are mixing some things.
As described in the documentation of the [BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function, the function returns a `list` containing 2 different elements : 

- `Compt.By.Species` : a `data.frame` containing the summary of range change for each comparison
- `Diff.By.Pixel` : a map containing a value for each point/pixel of each comparison among -2, -1, 0, 1

Hence, it is normal when you save the `Diff.By.Pixel` object as a raster that it does not contain the same values of the `Compt.By.Species` table whose values mean for example : over your whole map, 533 pixels were classified as Lost, 519 as stable absences, 503 as stable presences, 504 as Gained.

As for the values returned by the `BIOMOD_Modeling` and `BIOMOD_EnsembleModeling` functions, there are probabilities multiplied by 1000 to save space when saving the results, hence between 0 and 1000.
BUT you need to give binary maps to the [BIOMOD_RangeSize](https://biomodhub.github.io/biomod2/reference/BIOMOD_RangeSize.html) function, otherwise, the computation `proj.future−2∗proj.current` is not gonna be able to return you values among -2, -1, 0 or 1.

_By the way, please make sure you have the last version of the `biomod2` package installed, we added some warnings about these working cases :)_ 

Hope it helps,
Maya
