### ISSUE TITLE
Errors BIOMOD_EnsembleModeling()

### ISSUE THREAD

**Issue by FrancescoPola** [biomodhub/biomod2#133]
Hi,

I encountered a problem re-running a code that was working fine before the package update. 
I managed to run the models BIOMOD_Modeling() but the ensemble modeling throws errors BIOMOD_EnsembleModeling():

 # task 1 failed - "error in evaluating the argument 'obj' in selecting a method for function 'get_predictions': task 4 failed - "invalid class “GridTopology” object: cells.dim has incorrect dimension".

Has this happened to anyone else?

Many thanks,
Francesco

**Comment by rpatin** [comment]
Hi Francesco,
In the code you sent me your call to `BIOMOD_EnsembleModeling` was: 
```
myBiomodEM <-    BIOMOD_EnsembleModeling(
  myBiomodModelOut,
  models.chosen = "all",
  em.by = "all",
  metric.select = "TSS",
  metric.select.thresh = 0.4,
  metric.select.table = NULL,
  metric.eval = c("TSS", "ROC"),
  var.import = 3,
  prob.mean = FALSE,
  prob.median = FALSE,
  prob.cv = FALSE,
  prob.ci = FALSE,
  prob.ci.alpha = 0.05,
  committee.averaging = FALSE,
  prob.mean.weight = FALSE,
  prob.mean.weight.decay = "proportional",
  nb.cpu = 1,
  seed.val = NULL,
  do.progress = FALSE
)
```

The problem is that you set all ensemble models to `FALSE`, although at least one of them must be set to `TRUE` for the function to work. In other words you asked to do no ensemble models. I added a check in the next version so that the function throw a better error in such cases.

Best,
Rémi

**Comment by FrancescoPola** [comment]
Many thanks Rémi for your answer. 

It seems that in the BIOMOD_EnsembleModeling()
em.by = "all"

does not work, whereas other combinations in the manual run fine. But then we do not get the final consensus model that takes all sub-models into account?

Thanks for the clarification.

Best,
Francesco

**Comment by rpatin** [comment]
Hi Francesco,
Can you share the code you use to call `BIOMOD_EnsembleModeling()` and the error you get when you set `em.by = 'all'`  ?
Best,
Rémi

**Comment by FrancescoPola** [comment]
Hi Remi, 

the error is always the same: "Error in { : 
  task 1 failed - "error in evaluating the argument 'obj' in selecting a method for function 'get_predictions': task 4 failed - "Argument eta must be a nonempty numeric vector"

code:
myBiomodEM <-    BIOMOD_EnsembleModeling(
    myBiomodModelOut,
    models.chosen = "all",
    em.by = "all", 
    metric.select = "all",
    metric.select.thresh = NULL,
    metric.select.table = NULL,
    metric.eval = c("TSS", "ROC"),
    var.import = 0,
    prob.mean = F,
    prob.median = FALSE,
    prob.cv = FALSE,
    prob.ci = FALSE,
    prob.ci.alpha = 0.05,
    committee.averaging = F,
    prob.mean.weight = T,
    prob.mean.weight.decay = "proportional",
    nb.cpu = 5,
    seed.val = NULL,
    do.progress = T
  )


whereas if I use:
myBiomodEM <-    BIOMOD_EnsembleModeling(
    myBiomodModelOut,
    models.chosen = "all",
    em.by = "PA_dataset", # all not working
    metric.select = "all",
    metric.select.thresh = NULL,
    metric.select.table = NULL,
    metric.eval = c("TSS", "ROC"),
    var.import = 0,
    prob.mean = F,
    prob.median = FALSE,
    prob.cv = FALSE,
    prob.ci = FALSE,
    prob.ci.alpha = 0.05,
    committee.averaging = F,
    prob.mean.weight = T,
    prob.mean.weight.decay = "proportional",
    nb.cpu = 5,
    seed.val = NULL,
    do.progress = T
  )

it works just fine, but again in this way we are not getting the final consensus model that takes all sub-models into account, do we? 

Maybe I am missing something!

Thanks again,
Francesco

**Comment by rpatin** [comment]
Hi Francesco,

Indeed there is a bug when asking for ensemble models with  `em.by = "all"` or `em.by = "algo"` and having only a single pseudo-absences dataset, thank you for spotting it and sorry for the inconvenience. I updated a bugfix, so if you update to the current github version it should work.

Alternatively you can also work with >1 pseudo-absences dataset.

On a side note, I noticed that in your ensemble model you are merging repetitions (`RUN1` and `RUN2`) with your full models which is a bit odd for an ensemble model. I would suggest:
- Either you use full models (`Baetis_PA1_FULL_FDA`, `Baetis_PA1_FULL_GLM`) and merge them in an ensemble model so that you get an ensemble over algorithm (and eventually PA dataset)
- Or you use only your repetitions models (`Baetis_PA1_RUN1_FDA`, `Baetis_PA1_RUN2_FDA`, `Baetis_PA1_RUN1_GLM`, ...) and merge them over algorithm (or any other merge that suits you)

You can subset the models used in the ensemble using:
```
selected_models_nofull_models <- get_built_models(myBiomodModelOut)[! grepl(pattern = "Full", x = get_built_models(myBiomodModelOut))]

selected_models_onlyfull_models <- get_built_models(myBiomodModelOut)[grepl(pattern = "Full", x = get_built_models(myBiomodModelOut))]
```
and then use your selection with argument `models.chosen` in `BIOMOD_EnsembleModeling`:
```
myBiomodEM <- BIOMOD_EnsembleModeling(
  myBiomodModelOut,
  models.chosen = selected_models_nofull_models,
  em.by = "all",
  metric.select = "all",
  metric.select.thresh = NULL,
  metric.select.table = NULL,
  metric.eval = c("TSS", "ROC"),
  var.import = 0,
  prob.mean = F,
  prob.median = FALSE,
  prob.cv = FALSE,
  prob.ci = FALSE,
  prob.ci.alpha = 0.05,
  committee.averaging = F,
  prob.mean.weight = T,
  prob.mean.weight.decay = "proportional",
  nb.cpu = 5,
  seed.val = NULL,
  do.progress = T
)

```

Cheers,
Rémi

**Comment by FrancescoPola** [comment]
Hi Rémi, 

Thank you so much, now it works! And thanks about your suggestion, it definitively improved the code :)

Cheers,
Francesco
