### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by maurizioingrosso** [biomodhub/biomod2#137]
Hello,
I'm trying to install biomod2 with R version 4.2.1 but it does not install.
Returns this kind of error:
Warning in install.packages :
  cannot create dir '********R\win-library\4.2\file142c3f7679cb', reason 'Permission denied'
Error in install.packages : non è possibile creare una directory temporanea ‘**********R\win-library\4.2\file142c3f7679cb’

* substitute my directory

**Comment by rpatin** [comment]
Hello @maurizioingrosso 
Do you have the same kind of error when installing other packages ?
From what I have seen the error message may appear when rstudio have been installed as administrator but you are running it as a simple user (see [here](https://community.rstudio.com/t/whenever-i-dowload-any-package-it-says-failed-and-says-unable-to-create-file/21685/4 ) or [here](https://stackoverflow.com/questions/42807247/installing-package-cannot-open-file-permission-denied) ). In that case you would need to run Rstudio as administrator to be able to install packages (or redo the installation as a simple user which is generally better).
Cheers,
Rémi

**Comment by sandeepB055** [comment]
hello @rpatin 
i have a similar issue while trying to install the development version of biomod2. i used the devtools::install_github("biomodhub/biomod2", dependencies = TRUE) code but the package is not being installed. the warning begins with a message to install Rtools and indicates something about not being able to copy a file to some location. 

I'm running R as administrator and the documents folder (where the packages are installed into) is having full access permission. i wanted the development version as i ran into the 'TSS binary files not being created' which was fixed in this version. 
![image](https://user-images.githubusercontent.com/122000479/210710433-b66a626d-b12e-44b8-9726-00f59e947869.png)

please help,
best
Sandeep
