### ISSUE TITLE
Calculating the Distribution Area

### ISSUE THREAD

**Issue by ozgurhsyndgn** [biomodhub/biomod2#141]
Hello everyone,

I'm trying to calculate the total distribution of species on my current ensemble model (not SRC, not range shifts), 
is there any suggestions you can give me for doing so?

I've an ensemble model for current distribution of a species, what type of approach should I use to calculate it as "square kilometers"?

I've read all the document on CRAN about biomod2, but I couldn't find anything about it.

Thanks in advance for the answers.

PS: "sdm" package has the utility I'm mentioning about, it's something like this:

eez <- function(x){ # x = ensemble output, raster
  cell_size <- area(x, na.rm=TRUE, weights=FALSE)
  x <- cell_size*x
  result <- cellStats(x, sum)
  print(paste0(result," km2"))
  return(result)
}
to calculate
area_ponderada(rainforest_2650)
area_ponderada(rainforest_current)

**Comment by rpatin** [comment]
Hello @ozgurhsyndgn 
Thank you for reporting :pray:
Unfortunately there are no functions within `biomod2` to calculate the distribution area - although we may consider adding such feature in future release. You can however use the function from `sdm` package or re-use its code. Beware that within `biomod2` you need to do the calculation with a binary transformation of you model projection.
 
1. If you have a `SpatRaster` from library `terra` you can do the following:
```
# with terra
x <- terra::rast("GuloGulo/proj_Current/proj_Current_GuloGulo_TSSbin.grd") # load the binary transformation
cell_size <- cellSize(x, unit = "km")
x <- cell_size*x
result <- global(x, sum, na.rm = TRUE)
```


2. Alternatively, if you have a `RasterStack` from library `raster` you can do the following:
```
# with raster
x <- raster::stack("GuloGulo/proj_Current/proj_Current_GuloGulo_TSSbin.grd")
cell_size <- area(x, na.rm=TRUE, weights=FALSE)
x <- cell_size*x
result <- cellStats(x, sum)
```

In both situation `result` will be a vector with the distribution area in km² for all the models projected in `proj_Current_GuloGulo_TSSbin.grd`.

I hope this helps and if not, feel free to ask further questions.
Best,
Rémi

**Comment by ozgurhsyndgn** [comment]
Thanks for all those enlightening suggestions Remi,

I'll be trying them and giving back you the feedback as soon as possible. 

Respectfully

Huseyin

**Comment by ozgurhsyndgn** [comment]
I keep the post open for further suggestions from another users.

Cheers!

**Comment by chenyongpeng1** [comment]
Hi，everyone！
       
  How to calculate the loss area and obtain the area, stable area？

Cheers！

**Comment by rpatin** [comment]
Hi Chen,
I am not sure that your question is linked to the current issue that Huseyin opened. 

- If you have troubles with calculating change in range size given different scenario (e.g. Climate) and likely using `BIOMOD_RangeSize` can you please open a new issue and have a bit more explanation about what you have done yet and what you are trying to achieve.

- If your question is related to calculate range size for a given model, then it may be linked to what Huseyin was discussing, but again a bit more context on your question would be appreciated, and it will likely be also appropriate to open a new issue if you have a doubt.

In general we appreciate when each issue thread is limited to a single problem, that will be easier to follow for everyone, and especially for us so that we can help you efficiently :wink:

Cheers,
Rémi
