### ISSUE TITLE
GAM of biomod2 doesnot work sometime

### ISSUE THREAD

**Issue by tongruiju** [biomodhub/biomod2#152]
Hi Remi,

GAM of biomod2 doesnot work in modeling sometime. It seems related to the NO. of species presences and background points.
My code:  myBiomodModelOut<-BIOMOD_Modeling(bm.format = myBiomodData, bm.options = myBiomodOptions,models=c('GAM'), data.split.table = myBiomodCV,  prevalence=0.5, var.import=1, metric.eval=c('TSS', 'KAPPA', 'ROC'),  do.full.models=FALSE, modeling.id=paste(myRespName, "FirstModeling", sep=""), seed.val = 84, nb.cpu = 16)

biomod2 reported:
Model=GAM
	 GAM_mgcv algorithm chosen
	Automatic formula generation...
	> GAM (mgcv) modeling...
*** single value predicted
   ! Note :  SP_AllData_RUN1_GAM failed!

The warnings followed:
Warning messages:
1: In FUN(X[[i]], ...) :
  Parallelisation with `foreach` is not available for Windows. Sorry.
2: executing %dopar% sequentially: no parallel backend registered 
3: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Iteration limit reached without full convergence - check carefully
4: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Iteration limit reached without full convergence - check carefully
5: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Iteration limit reached without full convergence - check carefully
6: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Iteration limit reached without full convergence - check carefully

Thanks very much in advance!!!

Best wishes, 
Rui

**Comment by MayaGueguen** [comment]
Hello Rui,

The failing of the GAM model (or any other model in this case) associated with the message `single value predicted` is indeed not related to a bad behavior of the `biomod2` package rather than a modelisation problem.

Most of the time, you get this message when you do not have enough occurrence data (small number of points) or inadapted explanatory variables in the sense that they are not useful to explain your species niche. The model does not succeed to find _a combination / a rule_ to be able to say "_the species is present under these conditions but not these ones_", and therefore it predicts the species everywhere (or nowhere), and that's why you get the  `single value predicted` message.

Hope it helps,
Maya
