### ISSUE TITLE
Error in running BIOMOD_EnsembleModeling

### ISSUE THREAD

**Issue by Ellydelfin** [biomodhub/biomod2#161]
Since the new Biomod2, I keep getting this error
Error in { : task 2 failed - "subscript out of bounds"

 when running:
myBiomodEM <- BIOMOD_EnsembleModeling(
  bm.mod =myBiomodModelOutCalves,
  models.chosen = 'all',
  em.by='PA_dataset+repet',
  metric.select = c('ROC'),
  metric.select.thresh= c(0.65),
  prob.mean = T,
  prob.cv = T,
  prob.ci = T,
  prob.ci.alpha = 0.05,
  prob.median = T,
  committee.averaging = T,
  prob.mean.weight = T,
  prob.mean.weight.decay = 'proportional' )

I am using the same dataset I always had (never had any issue before) and I have just re-arranged the codes following the new version.

I'd really appreciate any help!

**Comment by rpatin** [comment]
Hello @Ellydelfin,
Thank you for reporting :pray: and sorry that the new version broke your script.

Your call to `BIOMOD_EnsembleModeling` looks good to me.
Note that with the new version (4.2-2) you should also be able to write the call as follows:
```
myBiomodEM <- BIOMOD_EnsembleModeling(
  bm.mod =myBiomodModelOutCalves,
  models.chosen = 'all',
  em.by='PA+run',
  metric.select = c('ROC'),
  metric.select.thresh= c(0.65),
  em.algo = c("EMmean","EMcv","EMci","EMmedian","EMca","EMwmean"),
  EMci.alpha = 0.05,
  EMwmean.decay = 'proportional')
```

Concerning the error you get, we would need a bit more information on the data you use as well as the previous modeling steps you did, in order to help you. Could you provide:
1. The code you used to call `BIOMOD_FormatingData`
2. The summary of `BIOMOD_FormatingData` output
3. The code you used to call `BIOMOD_Modeling`
4. The summary of `BIOMOD_Modeling` output
5. The full console output for your call to `BIOMOD_EnsembleModeling`

Cheers,
Rémi

**Comment by Ellydelfin** [comment]
Hi @rpatin,

thank you for the fast reply. I tried your code and I get this error:
Error in BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOutCalves, models.chosen = "all",  : 
  unused arguments (em.algo = c("EMmean", "EMcv", "EMci", "EMmedian", "EMca", "EMwmean"), EMci.alpha = 0.05, EMwmean.decay = "proportional")

For what concerns the information, here it is.
1. # the name of species/Group column
myRespName <- "Group"
# the presence/absences data for our species
myResp <- as.numeric(spdata[,1])
# the XY coordinates of species data
myRespXY <- spdata[,c("Long","Lat")]
#### organising data ####
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = envdata ,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)
2) summary(myBiomodData)
              Length                Class                 Mode 
                   1 BIOMOD.formated.data                   S4  

3) myBiomodOption <- BIOMOD_ModelingOptions(GAM = list( algo = 'GAM_mgcv',
                                                     type = 's_smoother',
                                                     k = 4),
                                         MAXENT.Phillips = list(
                                           maximumiterations = 500,
                                           threshold = FALSE))
### MAXENT.jar file needs to be in your working folder

####### Biomod models to be used. Can use more but selected 6 for now
myBiomodModelOutCalves <- BIOMOD_Modeling(
  myBiomodData,
  models = c('GLM','GAM','RF','ANN','MAXENT.Phillips'),
  bm.options = myBiomodOption,
  nb.rep=100, 
  data.split.perc=75,
  prevalence=0.5,
  var.import=5,
  metric.eval = c('TSS','ROC'),
  save.output = TRUE,
  scale.models = FALSE,
  do.full.models = FALSE,
  modeling.id = paste(myRespName,"ensemble",sep="."))

4)  Length             Class              Mode 
                1 BIOMOD.models.out                S4 

5)	Evaluating Model stuff...Error in { : task 2 failed - "subscript out of bounds"
In addition: There were 22 warnings (use warnings() to see them)


I will send an email with some screenshots in order to have a better idea of point 2, 4 and 5. 

Thanks for your support!

**Comment by Ellydelfin** [comment]
Hi Rémy,

I cannot attach the screenshots on the answer, so I thought I will also
answer here.

   1. the name of species/Group column
   myRespName <- "Group"
   the presence/absences data for our species
   myResp <- as.numeric(spdata[,1])
   the XY coordinates of species data
   myRespXY <- spdata[,c("Long","Lat")]

myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
expl.var = envdata ,
resp.xy = myRespXY,
resp.name = myRespName)

   1.

   summary(myBiomodData)
   Length Class Mode
   1 BIOMOD.formated.data S4
   2.

   myBiomodOption <- BIOMOD_ModelingOptions(GAM = list( algo = 'GAM_mgcv',
   type = 's_smoother',
   k = 4),
   MAXENT.Phillips = list(
   maximumiterations = 500,
   threshold = FALSE))

####### Biomod models to be used. Can use more but selected 6 for now
myBiomodModelOutCalves <- BIOMOD_Modeling(
myBiomodData,
models = c('GLM','GAM','RF','ANN','MAXENT.Phillips'),
bm.options = myBiomodOption,
nb.rep=100,
data.split.perc=75,
prevalence=0.5,
var.import=5,
metric.eval = c('TSS','ROC'),
save.output = TRUE,
scale.models = FALSE,
do.full.models = FALSE,
modeling.id = paste(myRespName,"ensemble",sep="."))

   1.

   Length Class Mode
   1 BIOMOD.models.out S4
   2.

   Evaluating Model stuff...Error in { : task 2 failed - "subscript out of
   bounds"
   In addition: There were 22 warnings (use warnings() to see them)

thanks again!
Elena

**Comment by rpatin** [comment]
Hi Elena,
Thank you for the additional informations :pray: 
Could you also share the results of:
1. `show(myBiomodData)`
2. `show(myBiomodModelOutCalves)`

Additionaly, I suppose you are using `biomod2` version `4.1-2` from CRAN ? 
However I did not manage to reproduce the error. 
You can:
- Try the latest version available on github with `devtools::install_github('biomodhub/biomod2')` maybe the error will solve itself with the new version.
- Alternatively I can have a look with your data if you can send them by mail (remi.patin@univ-grenoble-alpes.fr), this should help me reproduce the issue you encounters.

Cheers,
Rémi

**Comment by Ellydelfin** [comment]
Hi @rpatin ,

thank you for all the additional help, it is very useful. I managed using the latest version of Biomod 2 using the second option (downloding and using install command).

It seems to work now, but I will go through your suggestions with my colleague and see what we could change in order to increase the model performances. Do you think having some correlation or multicollinearity among some of the variables might be a cause of issues?  We decided to keep both bathymetry and distance to the coast, for example, but they do actually show a quite high degree of correlation.

For what concerns the background (absence) points we kept one point every 50 collected at 2-mins intervals, and further downsampled keeping one every 2 points in order to reduce the amount of them and get closer to the suggested proportion of presence/absence points. We still have a lot of absence points in some of the cells, which might be confusing for the algorithm maybe? We thought it would be useful to get higher resolution, but it might not be the case.

Thank you for all the explanations, it was enlightening!
Elena

**Comment by rpatin** [comment]
Hi Elena,
Glad that you could make it work. Here are a few additional answers:
- Correlation or multicollinearity among variables may hinder models convergence and your ability to identify which variables are important, but it is unlikely that it will affect the quality of the model as long the variable are relevant for the distribution.
- Concerning the background points, I had several remarks:
  1. When multiple points falls in the same cells (be it point from the same or different trajectory)  they will have the same values for environmental covariates and it is generally bad for the models to have repeated values. If that is happening a lot (i.e. because your boat always go through the same cells when leaving the port), it could explain why your models have low performance. Generally we advise keeping only one point per cell. There may be alternative ways of integrating the sampling effort but they are not integrated by default in `biomod2`. You can also follow the discussion [here](https://github.com/biomodhub/biomod2/discussions/165) that ask a tightly related question.
  2. Given that you kept only one point per cell, there is also a question of cell size. Maybe the link between your species presence and environmental layers is best explain at a larger scale (with larger cell size) than what you are using right now. It also depends on the question that you want to ask: using a finer scale could be useful for explaining the fine-scale habitat selection of your species but may also hinder your analysis to explain its large-scale habitat selection. As an (exaggerated) example if you have a cell size of 10m but want to predict general areas of 1km² or more, using such a high resolution will not be useful.
  
I hope this helps and feel free to ask if something is yet unclear.
Cheers,
Rémi

**Comment by Ellydelfin** [comment]
Hi Rémi,

hope you are doing well. I was wondering if you have any clue regarding the
issue my colleagues and I are trying to solve. We are using Biomod2 to
create an ensemble prediction of bottlenose dolphins distribution in
relation to 7 environmental covariates not correlated among them. We are
using presence/absence data (absence using the effort tracks without
animals, keeping only 1 out of 50 points to avoid autocorrelation).

We started developing these analyses with the old Biomod version, and used
(and still using) GLM, GAM, RF, MAXENT and ANN algorithms. We currently
have some weird results for ROC/TSS for Random Forest (and we tried with
GBM and have the same) which get almost to 1 without any SD. We are
puzzled by this, since we used not to have these results, and I am
wondering if there might have been some changes while getting from a
version to the new one of the package, which require us to make some codes'
modifications in relation to machine learning techniques.

I attach two plots of old and new ROC/TSS results.

Thank you for any help you might provide,
all the best
Elena
