### ISSUE TITLE
BIOMOD_Ensemble_Modelling File saving ERRORS

### ISSUE THREAD

**Issue by Arthur5245** [biomodhub/biomod2#170]
**Hi, thanks for this great package,
I'm trying the  biomod2 video: Single species modelling online tuto by Damien Georges
date: 2020-05-03
With Rstudio 2023.03.0 Build 257 and R 4.2.2. an the last version of BIOMOD2
When I run BIOMOD_Ensemble_Modelling :**
 

            ProLau_ensemble_models <- 
              BIOMOD_EnsembleModeling(
                models.chosen = "all",
                bm.mod = ProLau_models,
                em.by = 'all',
                metric.select = 'TSS',
                metric.select.thresh = 0.8,
                metric.eval = c('TSS','ROC'),
                em.algo = c("EMcv", "EMca", "EMwmean", "EMmean"),
                var.import = 0
              )
**I have the following errors for each Algo :**

            Error in { : 
              task 1 failed - "task 1 failed - "task 1 failed - "cannot open the connection"""
            In addition: Warning messages:
            1: In gzfile(file, "wb") :
                cannot open compressed file './Protea.laurifolia/.BIOMOD_DATA/demo1/ensemble.models/ensemble.models.predictions/Protea.laurifolia_EMcvByTSS_mergedData_mergedRun_mergedAlgo.predictions', probable reason 'No such file or directory'

**On my other PC with the same script but other versions of R (4.1.3) and Rstudio (1.2.5033) the results are saved in the "ensemble.models.predictions" for EMca and EMcv only**

**Here** is the script I use :
[biomod2_video_single_species_modelling.txt](https://github.com/biomodhub/biomod2/files/10490713/biomod2_video_single_species_modelling.txt)

**Thanks for your help,
Arthur**

**Comment by Arthur5245** [comment]
Thanks a lot,
Yes I use Windows.
I moved my working so that it has  a shorter path and it worked
Cheers

**Comment by brblais** [comment]
Hello,
I’m also receiving errors with task ‘1 failed … cannot open the connection’ and it seems users here and [other forums](https://r-forge.r-project.org/forum/forum.php?max_rows=75&style=nested&offset=282&forum_id=995&group_id=302) have had similar issues.
{Windows 11; R 4.1.1; Rstudio 2023.03.0 Build 386; biodod2 v.4.2-2}
I’m coding line by line from the updated tutorial guidelines (https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) and upon running the ‘#Model single species’ code, I get: 
**Error in { : task 1 failed - "cannot open the connection"**

My wd is local, short, and without odd characters. 
Getwd() #
[1] "C:/Users/opheo/Documents/R/Biomod2"

I created an empty ‘biomod2’ folder to work out of, and biomod2 code-generated subfolders (e.g., GuloGulo -> models -> …) themselves are being created…but the actual processing of model output is not. The error occurs immediately after running the single species code.

What might my issue(s) be? Should I have had additional “workdir” subfolders beneath my main working directory prior to running? 

- *Note: The same error occurs for regular or Cross-Validation dataset preparation and whether workdir is rooted on my local machine or flashdrive. I also get a “…cannot open the connection” error part-way through the ensemble model tutorial stage from the _Protea Laurifolia_ tutorial from the 5/2020 presentation. ...I'm trying to eventually get to multi-species ensemble modeling for my research and wanted to learn biomod2 via the tutorial(s) as a first step.  

Because several users are experiencing this issue, could you consider adding some lines of code in the tutorial overview for best practices on setting up directories and overcoming similar issues?  

Thank you, -Brian
