### ISSUE TITLE
Does a Biomod2 :: predict function is available ? 

### ISSUE THREAD

**Issue by Jmillot34** [biomodhub/biomod2#179]
Hi, 
I am currently modeling the distribution of a species using the new version of BIOMOD2 4.2.2. With an older version, I was able to use the function "predict" (not necessarily from the BIOMOD package) to make a prediction on a BIOMOD model. 

But now with the new version, I got an error message : 
"Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'predict2' for signature '"GAM_biomod2_model", "RasterStack" "

A BIOMOD :: predict function seems to exist but it is like the function is not recognized in R.

Any idea to resolve my issue? 

Thank you in advance for your help!

**Comment by rpatin** [comment]
Hi @Jmillot34, 
Thank you for reporting :pray:
The predict method that is currently implemented in `biomod2` v. 4.2-2 do not support `RasterStack`. So if you convert your object into a `SpatRaster` with `rast()` your command should be working fine.
Since version 4.2-1, we no longer use objects from package `raster` in our internal code, as the `raster` package is slowly being replaced by `terra`.
Cheers,
Rémi

**Comment by Jmillot34** [comment]
Thanks a lot, it works very well now!
