### ISSUE TITLE
Error in { : task 1 failed - "argument of length 0"

### ISSUE THREAD

**Issue by yuliaUU** [biomodhub/biomod2#181]
I am running the following code:
```

library(biomod2)
library(terra)
library(tidyverse)
# Load species occurrences (6 species available)
data("DataSpecies")

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
data("bioclim_current")
myExpl <- rast(bioclim_current)

#Transform true absences into potential pseudo-absences
myResp.PA <- ifelse(myResp == 1, 1, NA)
# Format Data with pseudo-absences : random method
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp.PA,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 2,
                                       PA.nb.absences =1000,
                                       PA.strategy = 'random')

myBiomodOption <- BIOMOD_ModelingOptions(SRE = list(quant = 0.05))

myBiomodModelOut <- BIOMOD_Modeling(
  myBiomodData,
  models = "SRE",
  bm.options = myBiomodOption,
  nb.rep = 2,
  data.split.perc = 70,
  weights = NULL,
  var.import = 0,
  metric.eval = c('ROC', 'TSS'),
  save.output = TRUE,
  scale.models = FALSE,
  do.full.models = TRUE
)
```

All runs wel, however this chunck produces 2 plots, i am not sure what plot 1 and plot 2 represent? different run or different pseaudoabsence?

```
# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = myBiomodModelOut)
```

While the rest of the plots does not work and give the error :`Error in { : task 1 failed - "argument of length 0"`

```
get_variables_importance(myBiomodModelOut)
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'algo'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('expl.var', 'algo', 'run'))
bm_PlotVarImpBoxplot(bm.out = myBiomodModelOut, group.by = c('algo', 'expl.var', 'run'))

```

I think it has smth to do with `expl.var` part: when i check `myBiomodModelOut` I can only see `myBiomodModelOut@expl.var.names` and no `expl.var`, so not sure if that is causing the issue?

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for providing the code and error :pray: 

```
# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = myBiomodModelOut)
```
- This first command indeed run like that gives you back 2 plots, but there are the same.
It it because, by default, the `do.plot` parameter in all plot functions is set to `TRUE` meaning that the plot will be rendered when running the function.
And the second one is because all `bm_Plot[...}` functions return a `list` containing both the data used to produce the plot, and the plot object to be able to reproduce the plot if wanted. As you don't put the result of the function into an object, it is plotted a second time. If you run the following, the plot will appear only once : 
```
# Not printing the plot by default
bm_PlotEvalMean(bm.out = myBiomodModelOut, do.plot = FALSE)

# Storing results into an object, you should not have any more prints into the console
myPlot = bm_PlotEvalMean(bm.out = myBiomodModelOut)

# This one should not print the plot nor outputs in the console at all
myPlot = bm_PlotEvalMean(bm.out = myBiomodModelOut, do.plot = FALSE)
```



- As for the second one : 
```
get_variables_importance(myBiomodModelOut)
```
It is simply because you did not calculate variables importance before, so there is nothing to return to you.
You should change the `var.import` parameter into the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function to a number > 0.

Hope it helps,
Maya

**Comment by yuliaUU** [comment]
Got it! thank you!
