### ISSUE TITLE
A new alternative tobinary_meth

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#191]
Hi, 
  After my model is built (myBiomodProj), I would like to get a classification map (unsuitable, low, high suitable area).
  Maybe biomod2 had this function before (binary_meth), but now how should I proceed? (biomod2 v4.2-2).
  Thanks

**Comment by MayaGueguen** [comment]
Hello Weicheng Ding,

`biomod2` projections are maps containing probability values between 0 and 1000 (or 0 and 1 if you set `on_0_1000 = FALSE`).
You can get binary maps (0 or 1) by using the `metric.binary` parameter within the [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) function : you select an evaluation metric which will be used to find the transformation threshold maximising this metric.
_For example, you select "TSS", and the function finds that when setting values > to cutoff = 456 to presences (1) and values < 456 to absences (0), you maximise your TSS value._
But this way, you get only 2 possible values : 0 or 1.

Otherwise, you can directly get your prediction values, and use the [cut](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/cut) function to transform your probability range into 3.

Hope it helps,
Maya

**Comment by 675979649** [comment]
Thank you for your reply！
The problem has been solved, but there is a new problem: when I run the project model, I want to select some models, but it reports an error.

myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
+                                   proj.name = 'Current',
+                                   new.env = myExpl,
+                                   models.chosen = c('CTA','FDA','GAM','GBM','MARS','MAXENT','SER'),
+                                   metric.binary = 'all',
+                                   metric.filter = 'all',
+                                   build.clamping.mask = TRUE)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Do Single Models Projection -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Error in .BIOMOD_Projection.check.args(bm.mod, proj.name, new.env, new.env.xy,  : 
  No models selected

**Comment by MayaGueguen** [comment]
Hello there,

The error message you get tells you that no models have been selected.
Could you check and send the output of the following lines please ?
To verify that you actually have models that worked at the modeling step.
``` 
print(myBiomodModelOut)
get_built_models(myBiomodModelOut)
```

Maya

**Comment by MayaGueguen** [comment]
Hello,

I'm sorry but I don't see what is the error you are talking about here ?
If it is that you do not "see" results into your RStudio environment, it is normal. All results are automatically saved on disk within your working directory. Regarding the information given by your `print(myBiomodProj)`, your simulation folder is `A.glabripennis` and your projection folder is `A.glabripennis/Current/`. Your output files should be within these folders.

The documentation at the `Value` paragraph into the help of [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function details this folder organization.

Maya
