### ISSUE TITLE
How to get fit grid layers of different models at each run

### ISSUE THREAD

**Issue by mengjiezhang4ds** [biomodhub/biomod2#201]
Dear biomod2 developer, hello!
In the 3.5 version of biomod2, I can easily get the results of different models in different rounds(RUN1 RUN2...) by accessing folders.
[![ppeCtVP.png](https://s1.ax1x.com/2023/03/07/ppeCtVP.png)](https://imgse.com/i/ppeCtVP)
But after upgrading to the 4.2 version, I found that these files disappeared. Only through plot(myBiomodProj) can I get the corresponding graphics, and myBiomodProj is an S4 object. I can't get any grid data from him. Maybe I haven't found it yet, so what should I do?
Thank you in advance for your help!

**Comment by MayaGueguen** [comment]
Hello there,

Thank you for updating `biomod2` to current version 🙏 

We added a new parameter in [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions : `do.stack`.

- When you set `do.stack = TRUE`, all projections are saved in one `SpatRaster` object.
- When you set `do.stack = FALSE`, each projection is saved in one `SpatRaster` object, so you get as many files as projections. AND if maps are too heavy, this `do.stack` is automatically set to `FALSE` so not all files are loaded at the same time in memory.

Here, your maps should be light enough so `do.stack` is set to `TRUE` and you should have one `SpatRaster` file in your folder containing directly all the projections. You can open them with the following commands : 
```
## With raster package
library(raster)
allProj = stack("yourprojectionfile.img")

## With terra package 
library(terra)
allProj = rast("yourprojectionfile.img")
```

Hope it helps,
Maya

**Comment by mengjiezhang4ds** [comment]
您好！我已收到你的来信，一般我会在每天23：00阅读邮件，如有重要事情请直接电话联系--15357902809。非常感谢来电！张梦杰

**Comment by mengjiezhang4ds** [comment]
Hello!
Thank you very much for answering my questions in your busy schedule. 
Recently, I was studying version 4.2 of **biomod2**. I found that the visualization of version 4.2 of **biomod2** is more beautiful than that of version 3.5, and the function interface is refined (rich functions, fine data return results). For example, a _do.stack_ parameter can save a lot of internal storage space. Thank you very much for your work and contributions!

Here I also have some experience to share with you

1. The core functions of biomod2 v4.2 should be completed on the basis of the extension package **caret**. I found that both error messages and cross-validation parameters are similar to some function results of **caret.** Thank you for your continuous updates.
2. On the Windows system, I want to build a model based on multiple species distribution data, but the multithreading setting cannot be parallelized because of the bug in the extension package **parallel**. I also tried the **snow** extension package, which also failed, but when I tried to downgrade to 3.5, it worked. However, I chose to run it directly with the _lapply_ function, which took a little longer. The 8 core laptop ran for 2 hours. Of course, I'm not in a hurry to solve this problem. I hope to see this problem solved in the future. I wish you success.

3. I have used **caret**, **tidymodels**, **h2o** and other frameworks to build species distribution models. I found that while maintaining the same data and other factors, **biomod2** takes much longer to build models than these frameworks. I don't know why. For example, if I want to use **tidymodels** to build a model, I will use **raster** _extract_ function to get the environmental data corresponding to the species data, and then directly get the data frame to build a model using **tidymodels**. At this time, it is very convenient to start multithreading to adjust parameters and make predictions (using the **h2o** expansion package is especially obvious, and the speed is like flying on an airplane, which is crazy). So I'm thinking that **biomod2** is developed based on **caret**. Why its speed much higher than that? I really appreciate any of your guesses!
Thank you in advance for your reply!

**Comment by MayaGueguen** [comment]
Thank you very much for your feedbacks on the new `biomod2` version 🙏 
It is really much appreciated by the team ❤️ 

Thanks also for all your comments and suggestions, it is always good to have external point of view.
We will try to give it a look and explore them as much as possible.

Here are some comments : 
1. We are currently not using a lot the `caret` package, except within the [BIOMOD_Tuning](https://biomodhub.github.io/biomod2/reference/BIOMOD_Tuning.html) function (`trainControl` function) and to apply `gam` model through `mgcv` package. It might also be called internally but we did not really based our development on this package, so similarity in messages / outputs were not on purpose.
Please note that we have a middle term development plan, including in short term to re-build cross-validation functions, and later to update used algorithms and their optimisation.

2. Yes, parallelization does not work on Windows for now, sorry for that. But version 3.5 was not parallelized at all. We also already improved a lot workflow since 3.5 version, so it is a bit smoother now, but simulations if numerous will eventually always take time at some point.

3. It might come from the fact that `biomod2` has more functionalities around the building of the models in itself, like pseudo-absences preparation, variables importance calculation, projections... But it is always cool to compare with other existing workflows and we will explore as much as possible these other possibilities 🌞 

Thanks again for all the suggestions !
Maya

**Comment by mengjiezhang4ds** [comment]
您好！我已收到你的来信，一般我会在每天23：00阅读邮件，如有重要事情请直接电话联系--15357902809。非常感谢来电！张梦杰
