### ISSUE TITLE
the TSS binary threshold seems not the one maximizing sum of sensitivity and specificity

### ISSUE THREAD

**Issue by tongruiju** [biomodhub/biomod2#202]
Hi Remi,

You mentioned the TSS binary threshold is determined as the cutoff maximizing sum of sensitivity and specificity, whilst ROC binray threshold is  determined as the cutoff maximizing ROC value,  to my previous question. But it shows that the sum of sensitivity and specificity in same row with ROC statistics is the maximum value, rather than  the ones in same row with TSS, such as following ones, 

![p1](https://user-images.githubusercontent.com/101609973/223584169-9e506386-b5a9-4f8c-824f-42ce248dae9c.png)
![p2](https://user-images.githubusercontent.com/101609973/223584176-524b66ac-f126-4590-9bf3-cba30472440e.png)

Does that mean the ROC binary map created by following sentence use the cutoff of maximizing sum of sensitivity and specificity?
Cheers,
Ruiju

**Comment by MayaGueguen** [comment]
Hello Ruiju,

Could you enlight me please where the evaluation values you show come from ?
Are they values for single models ? for ensemble models ? What are the rows and columns of the table ? 👀 

Also, could you please copy / paste console outputs rather than pasting screenshot please ?
It is easier for us to work with, and it allows other users to find issues when they have similar problems. 🙏 

Thanks in advance,
Maya

**Comment by tongruiju** [comment]
Hi Maya, 

Thanks very much for asking.

The evaluation is the output after code **myBiomodModelEval <- get_evaluations(myBiomodModelOut,as.data.frame = TRUE)**, and wroten in csv.

Each of the two figures is for a single model. Just two examples. 
The rows as you can see are kappa, roc and TSS, whilst the columns are Testing.data, Cutoff, sensitivity and specificity as exported.

I hope it is clear now. Many thanks.

Best, 
Ruiju

**Comment by MayaGueguen** [comment]
Hello Ruiju,

Thank you for the additional information 🙏 
Regarding the column names in your table, I think you are not using the last `biomod2` version.
We made some updates and corrections concerning the calculation of evaluation metrics within the last version.

Could you please try and update your `biomod2` package with the following commands please ?
```
library(devtools)
install_github("biomodhub/biomod2")
```

Maya

**Comment by MayaGueguen** [comment]
Hello Ruiju,

We thank you for that 🙏 but we did a lot of new changes since then :) 
I guess you should then have the 4.1-3 version. We are now at the 4.2-2, and the correction you're looking for should be at least in the 4.2-1 version. If you update directly to the last one with the `install_github` command, you would have a much more stable and up-to-date version, and it will also be easier for us to help you 🌞 

Maya
