### ISSUE TITLE
Weird error message when using the BIOMOD_Projection command

### ISSUE THREAD

**Issue by Nickmofoe** [biomodhub/biomod2#207]
So I read this paper (https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.2041-210X.2011.00172.x) that tries to clarifies the way to choose settings for PA and PA repetition. I had previously done test runs with less repetitions and now I tried to run it with the recommended 10 repetitions and 100 PAs. The test runs went pretty well but the runs I did know produced this error message: 

```
Error: [rast] cannot open this file as a SpatRaster: (file path Redacted)/proj_current_C.codringtonii.grd
In addition: Warning message:
`(file path Redacted)/proj_current_C.codringtonii.grd' not recognized as a supported file format. (GDAL error 4) 
```

Now I tried to reduce the PAs to 9 and I did not get this error message. Does anyone know why that happened and what I can do to fix it?

**Comment by rpatin** [comment]
Hello there,
Thank you for reporting :pray: 
If I understood well:
1. you ran a code with few repetitions and PAs, which worked well.
2. you ran the same code with 10 repetitions and 100 PAs, but the call to `BIOMOD_Projection` failed.
3. you ran the same code with 9 repetitions and 100 PAs and it worked again.

Concerning your error, I believe this can happen if the projection file was created, but the writing of the files was interrupted (maybe due to lack of memory?). Then when loading the files internally you would see that.

Could you share:
- the output of `sessionInfo()`
- the summary of your data and modeling outputs (`show(myBiomodData)` and `show(myBiomodModelOut)`)
- the code you used to call `BIOMOD_Projection`

Thanks in advance,
Rémi

**Comment by Nickmofoe** [comment]
So, after making these changes the projection worked! Thank you very much!
