### ISSUE TITLE
Error in tutorial  **Error in { : task 1 failed - "cannot open the connection"**

### ISSUE THREAD

**Issue by rpatin** [biomodhub/biomod2#226]
Hello,
I’m also receiving errors with task ‘1 failed … cannot open the connection’ and it seems users here and [other forums](https://r-forge.r-project.org/forum/forum.php?max_rows=75&style=nested&offset=282&forum_id=995&group_id=302) have had similar issues.
{Windows 11; R 4.1.1; Rstudio 2023.03.0 Build 386; biodod2 v.4.2-2}
I’m coding line by line from the updated tutorial guidelines (https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) and upon running the ‘#Model single species’ code, I get: 
**Error in { : task 1 failed - "cannot open the connection"**

My wd is local, short, and without odd characters. 
Getwd() #
[1] "C:/Users/opheo/Documents/R/Biomod2"

I created an empty ‘biomod2’ folder to work out of, and biomod2 code-generated subfolders (e.g., GuloGulo -> models -> …) themselves are being created…but the actual processing of model output is not. The error occurs immediately after running the single species code.

What might my issue(s) be? Should I have had additional “workdir” subfolders beneath my main working directory prior to running? 

- *Note: The same error occurs for regular or Cross-Validation dataset preparation and whether workdir is rooted on my local machine or flashdrive. I also get a “…cannot open the connection” error part-way through the ensemble model tutorial stage from the _Protea Laurifolia_ tutorial from the 5/2020 presentation. ...I'm trying to eventually get to multi-species ensemble modeling for my research and wanted to learn biomod2 via the tutorial(s) as a first step.  

Because several users are experiencing this issue, could you consider adding some lines of code in the tutorial overview for best practices on setting up directories and overcoming similar issues?  

Thank you, -Brian

_Originally posted by @brblais in https://github.com/biomodhub/biomod2/issues/170#issuecomment-1489436101_

**Comment by rpatin** [comment]
Hi @brblais,
Thank you for reporting :pray:
I suppose you have a different issue from https://github.com/biomodhub/biomod2/issues/170 so I opened a new issue, it is easier for everyone ;-)

The error `Error in { : task 1 failed - "cannot open the connection"` is quite generic and may be caused by many different problems. One of them being the long path length on windows, which is likely not your problem here, as you stated.

On my computer, I have no problem running the [tutorial](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) with biomod2 4.2-2. Note that there are no section  ‘#Model single species’ however in this tutorial. 

Therefore, could you give us a bit more information about your issue:
-  were you running the tutorial or the _Protea Laurifolia_ example from the online course ? 
-  what was the command you gave that produce an error and the console output before the error ? `biomod2` function communicate quite a lot and there are often explanation as to why error are happening.

Best,
Rémi

**Comment by brblais** [comment]
Thanks for the help, @rpatin 

I was able to run the updated biomod2 4.2 [tutorial ](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) with the single species (_Gulo gulo_) after:
1. restarting R
2. Opening the R script directly from the working directory folder (i.e., starting in the workdir rather than routing to it...which seemed to cause issues)
3. Not having separate subfolders (e.g., the 3 subfolders from the [2020 tutorial](https://github.com/biomodhub/biomod2-tutorial-material)) 

With such, I was successfully able to run through the (updated) sample tutorial "main functions" (e.g., single model, projection, ensemble, range size). 

However, I cannot get multi-species --via the [wrapper code from 2020](https://github.com/biomodhub/biomod2-tutorial-material/blob/master/biomod2_video_multi_species_modelling.zip) -- to run. I get "`NULL value passed as symbol address`" errors whether I try coding verbatim from the ca. 2020 script (_Larus_ dataset) or manually updating function nomenclature from v4.2 (attached .txt). ...I suspect I should open a new issue thread for that though? Unless there is an updated tutorial for multi-species wrappers somewhere?

Grateful for any assistance,
-Brian

[biomod_multspecies_error.txt](https://github.com/biomodhub/biomod2/files/11128001/biomod_multspecies_error.txt)

**Comment by rpatin** [comment]
Hi Brian,
Great that you were able to run the updated tutorial.
Concerning the multispecies error, you suspected well, it is indeed best to have a new thread. I already opened it though (https://github.com/biomodhub/biomod2/issues/227).
Best,
Rémi
