### ISSUE TITLE
Calculating validation values for the ensemble model 

### ISSUE THREAD

**Issue by Nickmofoe** [biomodhub/biomod2#231]
Greetings! I require help with calculating the validation values for the ensemble models as the title suggests. This is what I have done so far: 
```
(consider all the data imported)

#formatting data
#name
myRespName<- 'C.codringtonii'
myResp<- as.numeric(unlist(occ_cod[myRespName]))
#coordinates
myRespXY<- occ_cod[c("x","y")]



mybiomoddata<-  BIOMOD_FormatingData(
  myRespName,
  myResp,
  greece,
  dir.name = ".",
  myRespXY,
  eval.resp.var = NULL,
  eval.expl.var = NULL,
  eval.resp.xy = NULL,
  PA.nb.rep = 10,
  PA.nb.absences = 100,
  PA.strategy = "random",
  PA.dist.min = 0,
  PA.dist.max = NULL,
  PA.sre.quant = 0,
  PA.user.table = NULL,
  na.rm = TRUE,
  filter.raster = TRUE
)

#cross validation


mybiomodcv <- BIOMOD_CrossValidation(bm.format = mybiomoddata,
                                           k = 5,
                                           do.stratification = FALSE,
                                           nb.rep = 3,
                                           do.full.models = FALSE)



##Tuning the model 


time.seq <- system.time(
  bm.tuning <- BIOMOD_Tuning(bm.format = myBiomodData, ME.env = myExpl, ME.n.bg = ncell(myExpl), models = c('RF','GBM','ANN','GLM'))
)

myBiomodOptions <- bm.tuning$models.options



#model   

myBiomodModelOut <- BIOMOD_Modeling(
  mybiomoddata,
  models = c('RF','ANN','GBM','GLM'),
  bm.options = biomodoptions ,
  nb.rep= 3,
  data.split.table = myBiomodCV, 
  data.split.perc= 70,
  prevalence= 0.5,
  metric.eval = c('ROC','TSS'),
  var.import = 10)
  
  

#ensemble
codEnsemblemodel<-BIOMOD_EnsembleModeling(bm.mod = myBiomodModelOut,
                                          models.chosen ='all',
                                          em.by = 'all',
                                          metric.select = c('TSS'),
                                          metric.select.thresh = c(0.7),
                                          var.import = 10,
                                          metric.eval = c('TSS', 'ROC'),
                                          em.algo = c('EMmean', 'EMwmean','EMca','EMcv'),
                                          EMci.alpha = 0.05,
                                          EMwmean.decay = 'proportional')

#ensemble model eval
codensemblemodelscores <- get_evaluations(codEnsemblemodel)
get_variables_importance(codEnsemblemodel)

  sensitivity specificity calibration validation evaluation
1         100      97.579       0.977         NA         NA
2         100      97.895       0.994         NA         NA
3         100      97.684       0.978         NA         NA
4         100      98.105       0.994         NA         NA
5         100      98.632       0.986         NA         NA
6         100      98.632       0.996         NA         NA



```

As you can see, I have made the CV object which I integrated in the ```BIOMOD_Modelling``` function. I checked to see if the ```BIOMOD_EnsembleModeling``` has a similar parameter but it does not appear to have one. I also tried reducing the ```metric.select.thresh``` parameter from 0.7 to 0.6 but that didnt help either. If you can help me with that I would very much appreciate it! (This is the last question I ask I swear)

**Comment by rpatin** [comment]
Hi @Nickmofoe,
Thank you for reporting :pray: 
Everything looks fine with your output :ok_hand: 
The issue is that you cannot have validation metric when using `em.by = 'all'`. As you are merging individual models with different dataset (different pseudo-absence but also cross-validation dataset), there are no way to split the data used for the ensemble model between a calibration (training) and a validation dataset. Hence all data is pooled together as calibration.
If you want some kind of independent evaluations for your ensemble models you can:
1. use `em.by = `PA+run` but you will then get several ensemble models
2. use an independent evaluation dataset, using arguments `eval.resp`, `eval.xy` and/or `eval.env.data` in `BIOMOD_FormatingData`

Also, note that when you give your own cross-validation table to `BIOMOD_Modeling`, using argument `data.split.table` the other cross-validation arguments for `BIOMOD_Modeling` (`nb.rep` and `data.split.perc`) are ignored. Either you use the internal random crossvalidation or your own method but not both.

I hope this is clearer now. If not, feel free to ask additional questions,
Best,
Rémi
