### ISSUE TITLE
Is there a way to import the ```.out``` files that biomod generates?

### ISSUE THREAD

**Issue by Nickmofoe** [biomodhub/biomod2#235]
So my models take a while to run to completion and I often have to cut it short due to limited resources on my end. Is there a way for me to import the ```.out``` files for both the ensemble models and the respective ones? Thanks a lot!

**Comment by rpatin** [comment]
Hi @Nickmofoe 
To load `.out` files you just have to do `myObject <- get(load("myfile.out"))`. 
However it will only work for models/ensemble models for which the function run to the end. If your function failed in the middle of a run due to limited resources, you cannot start again in the middle of the run.
Feel free to precise your question if need be.
Best,
Rémi
