### ISSUE TITLE
Assistance is needed in interpreting the results of random forests and ensemble models.

### ISSUE THREAD

**Issue by Wonhyeop** [biomodhub/biomod2#247]
My question is closer to model interpretation rather than code. I would appreciate it if you could provide an answer.

1) Did I set up the model incorrectly if the AUC and TSS values of the random forest model are very high and close to 1 compared to other models? This issue often occurs in many cases.

2) Can you explain why an ensemble model may not perform better than some individual models? Most papers seem to show that ensemble models outperform individual models.

**Comment by rpatin** [comment]
Hi @Wonhyeop,
Thank you for reporting :pray: 
1. There are a few explanations for that:
   1. RF may indeed outperform other models or be more stable in its performance
   2. Some models included in `biomod2` are quite old and not all of them are expected to have good performance. Which are the one that are generally outperformed ?
   3. Model performance may depend on the parameters used and maybe in the situation you encountered the parameters used for RF were more appropriate than those used for the other models. In theory you could use `BIOMOD_Tuning` to optimize the parameters used. However the function is quite old and not that much practical (but it can be worth testing). _A rework of the function is planned for next release_
   4. If your RF AUC or TSS are systematically very high and close to 1 it may be suspicious indeed. But without a practical example (dataset + modeling workflow) it is hard to give advice. 

2. There are also a few answers possible for that:
   1. Ensemble models performance relies on individual models. If you have individual models with low performance that participate to your Ensemble model, they may hinder the EM performance (though this is less the case for a weighted mean EM for instance). How do you set the threshold to choose whether individual models should be included in the EM ? It can also depends on the parameters used in the individual models (see the point above).
   2. Ensemble models may outperform individual models, but this can also depends on how you measure performance, for instance on which dataset (cross-validation, independent dataset with few or many extrapolation required). 
 
I hope this answer part of your questions. Feel free to elaborate or add some context.
Best regards,
Rémi

**Comment by Wonhyeop** [comment]
Thank you for your quick response.

1.iv. I generated 10,000 pseudo-absence data points using only occurrence data, and then treated these data points as "NA". After that, I ran the following code. RF model shows very high ROC and TSS values.

`myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                            expl.var = myExpl,
                                            resp.xy = myRespXY,
                                            resp.name = myRespName,
                                            PA.nb.rep = 3,
                                            PA.nb.absences = 10000,
                                            PA.dist.min = 10000, 
                                            PA.strategy = 'random',
                                            filter.raster = TRUE `

`myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                           models = c("GLM", "GBM", "GAM", "CTA", "ANN", "FDA", "MARS", "MAXENT", "SRE", "RF"), 
                                           bm.options = myBiomodOption,
                                           nb.rep = 3,
                                           data.split.perc =70,
                                           prevalence = 0.5,
                                           var.import = 1,
                                           metric.eval = c('TSS','ROC'),
                                           save.output = TRUE,
                                           do.full.models = FALSE`

![RF의 이상치](https://user-images.githubusercontent.com/125497148/233335847-7341c26e-934d-42f7-8c62-090f5bacd6e4.JPEG)


and the SRE map result appears as a binary map, which is an unusual phenomenon. I am not sure why this is happening.

![map result](https://user-images.githubusercontent.com/125497148/233340023-58db0fb0-1cbe-4592-bf70-af460076d2cf.JPEG)


2.i. I ran an ensemble model using single models with AUC values over 0.6 because the TSS value was too low, below 0.4.

3. I am trying to use the CV.strategy function as shown below, but it says that the function does not exist. What did I do wrong? My biomod2 version is 4.2.3.

`myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                         models = c("GLM", "GBM", "GAM", "CTA", "ANN", "FDA", "MARS", "MAXENT", "SRE", "RF"), 
                                         bm.options = myBiomodOption,
                                         CV.strategy = 'random',
                                         CV.nb.rep = 2,
                                         CV.perc = 0.8,
                                         nb.rep = 3,
                                         data.split.perc =70,
                                         prevalence = 0.5,
                                         var.import = 1,
                                         metric.eval = c('TSS','ROC'),
                                         save.output = TRUE,
                                         do.full.models = FALSE)`

**Comment by rpatin** [comment]
Hi @Wonhyeop,
Thank you for the update :pray:
Please avoid posting screenshot when you can copy-paste the results (e.g. for errors or console outputs)
First, I can answer the 3 and 4 and the comment on the SRE:

3. You need to update again your `biomod2`, we did not update the version number on `github` so the new version is still called 4.2-3 but will work with argument `CV.strategy`. Additionnaly you can omit argument `nb.rep`, `data.split.perc` and change `do.full.models` into `CV.do.full.models`. Other argument should be fine.

4. evaluation values are returned when you provide an independent evaluation dataset to  `BIOMOD_FormatingData`. e.g. you work on France but evaluate model performance with data from Belgium. If you do not have such independent dataset (in most cases) you can still do cross-validation.

Also, SRE is a binary model, so its predictions are expected to be either 0 (outside of environmental range) or 1 (inside environmental range), so everything looks OK. It is also expected to be a pretty bad model as it is quite restricted in how it models species-environment relationship.

For the other points I may need a bit more time but if you can provide some additional information that would be great:
- can you show projection maps for one or two other models ?
- can you show the data plot ? `plot(myBiomodData, plot.type = "raster")`
- what is the resolution of the map you are using ?
- what kind of environmental data are you using ?

Best regards,
Rémi

**Comment by Wonhyeop** [comment]
The issue with questions 3 and 4 has been resolved. Thank you very much.

I will provide an answer to your request.

- can you show projection maps for one or two other models ?
![image](https://user-images.githubusercontent.com/125497148/233401540-01e127ca-2f23-428e-a9cf-ac86842a2e56.png)
- can you show the data plot ? plot(myBiomodData, plot.type = "raster")
![image](https://user-images.githubusercontent.com/125497148/233396049-8d5be639-9d7d-4ba5-97c0-1ce4387caef0.png)
- what is the resolution of the map you are using ?
1km
- what kind of environmental data are you using ?
After conducting multicollinearity tests on 19 bioclim, slope, dem, and aspect variables, only 5 bioclim variables that passed the tests were used for modeling.
![image](https://user-images.githubusercontent.com/125497148/233400088-c644cc2d-376d-4e28-a06e-1ed4fe84532e.png)



If the RF value keeps coming out high, should I exclude it?

**Comment by rpatin** [comment]
Hi @Wonhyeop,
Thank you for the additional information :pray:
After a bit of thinking with Maya, we came up with the following answers (and questions).

First, we noticed that the pseudo-absence that you showed were most likely selected with the `disk` method, though your code indicated that you used the `random` method. Could you make sure to share the code for `BIOMOD_FormatingData` that correspond to the one you used ? Additionally, could you share the output of `show(myBiomodData)` ? We were curious to check the number of presence and pseudo-absence generated in the object.

It is quite interesting to see that `RF` is performing very well while the other models are not. Also note that the other models predictions look quite consistent, which is a good thing. With that said, there are two possibilities:
1. `RF` is overfitting the data, so its high performance is not a good thing and you should likely exclude the model or implement changes to avoid `RF` overfit.
2. `RF` model is actually satisfying, while the other model's performance are underwhelming. Then you would be better at using only `RF` or try improving the other models performance (e.g. through better parametrisation).

To decide between 1 and 2 you have to ask yourself whether `RF` models looks satisfying:
- Are projections consistent with your ecological knowledge of the species ? In other words: are projections (or binary projection that are sometimes easier to read) appropriate or do they have a lot of fine-scale holes and peaks that are not ecologically meaningful ?
- How does the response to the environment looks like ? You have to look at the output of `bm_PlotResponseCurves` especially for `RF`. If the response curves are ecologically meaningful, then it would validate the model. Otherwise if response curves are highly complex with lots of peaks and valley, it would be a clear indication of overfit. Could you share such plot for the issue ?

If you have hints that `RF` models is indeed satisfying, then you could try to improve you other models. Ideally I would suggest you to use `BIOMOD_Tuning` but it is not quite usable nowadays. It does not work with pseudo-absence dataset for instance. We have planned a major rework of `BIOMOD_Tuning` but it will only be ready in several months. To explore this idea you can however try to tweak slightly models parameter, for instance by increasing the number of trees used in `GBM`:
`myBiomodOption <- BIOMOD_ModelingOptions(GBM = list(n.trees = 5000))`

If you have hints that `RF` models are overfitting you can try to limit the overfit:
- You can tweak `RF` parameters and decrease the number of trees or decrease size of tree:
   - `myBiomodOption <- BIOMOD_ModelingOptions(RF = list(ntree = 250))`
   - `myBiomodOption <- BIOMOD_ModelingOptions(RF = list(nodesize = 10))` # here increase of nodesize decrease the size of trees
- You can also try to select your pseudo-absences differently. It is likely here that `disk` pseudo-absences may favor overfit in `RF` while `random` pseudo-absence would likely be more neutral towards that.

Hope this helps for your issue. Feel free to update with additional information or questions.
Best,
Rémi
