### ISSUE TITLE
Help with BIOMOD_FormatingData : error using a test dataset

### ISSUE THREAD

**Issue by AuTh5** [biomodhub/biomod2#260]
Hello all,

I am working with biomod2 to implement random forests and gradient boosting machines using presence-only data. Starting with the BIOMOD_FormatingData and using other biomod2 functions, I successfully generate several models with several pseudo-absence datasets while submitting only a training dataset to be divided into a calibration and validation dataset. 
My problem is :
I now want to submit a test dataset (the training dataset includes 10 years and I want to test the model on the following 2 years of data) to the BIOMOD_FormatingData function. My resp.var, expl.var, eval.resp.var and eval.expl.var are all SpatVectors created using different subsets from the same dataframe (normdata and eval are subsets of one original dataframe). First, I tried giving presence-only data as the eval.resp.var since the function generates the pseudo-absences :

```

prestrainUE <- vect(normdata[,1:3], geom=c("x","y"))
trainexpl <- vect(normdata[,2:62], geom=c("x","y")) 
(Please note the former are the two objects I used to successfully run models before)
presevalUE <- vect(eval[,1:3], geom=c("x","y"))
evalexpl <- vect(eval[,2:62], geom=c("x","y"))

myBiomodData.rd <- BIOMOD_FormatingData(
                                        resp.var = prestrainUE,
                                        expl.var = trainexpl,
                                        resp.name = 'wnv',
                                        eval.resp.var = presevalUE,
                                        eval.expl.var = evalexpl,
                                        PA.nb.rep = 30,
                                        PA.nb.absences = 895,
                                        PA.strategy = 'random')

```

but I got the following error :

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-= wnv Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=
!   Response variable have non-binary values that will be converted into 0 (resp <=0) or 1 (resp > 0).Erreur dans .check_formating_resp.var(resp.var = eval.sp, eval.data = TRUE) : 
Evaluation response data must have both presences and absences

```

I then tried generating one set of pseudo-absences for the test dataset and created a SpatVector for eval.resp.var but I get the following error :

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= wnv Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
!   Response variable have non-binary values that will be converted into 0 (resp <=0) or 1 (resp > 0).
! NAs have been automatically removed from Evaluation dataErreur dans .check_formating_expl.var(expl.var = eval.env, length.resp.var = length(eval.sp)) : 
If explanatory variable is not a raster then dimensions of response variable and explanatory variable must match!

```

The resp and expl vars for the training dataset both have the same number of lines, different numbers of columns, which worked perfectly fine when I did not submit a test dataset. The resp and expl vars for the test dataset are built the exact same way and are different from one another just like the former. 
Even if I found out a way to make the second method work, I would still want to implement 30 different predictions using 30 pseudo-absence datasets for my 2 years of test dataset, which I think would still require to use biomod formated data including PA.

I have been trying to understand where I got it wrong but I can’t seem to find a solution, I will gladly take any idea :) Thanks

**Comment by rpatin** [comment]
Hello @AuTh5,
Thank you for reporting :pray: 

When you use an `evaluation` dataset (in opposition to `cross-validation`), you need to provide `eval.resp.var` with both `0` and `1`, hence the first error:
```
Evaluation response data must have both presences and absences
```
Then, I suppose you gave a mix of `1`, `0` and `NA`, which is not handled by our code - sorry for that. Can you share the output of `summary(presevalUE)` to confirm that ? Once you correct `presevalUE` to have only `0` and `1` this should fix your first issue.

For your second issue:
> I would still want to implement 30 different predictions using 30 pseudo-absence datasets for my 2 years of test dataset

If I understood well you want to build 30 different evaluation dataset so that each model that you built is evaluated 30 times, each time with the same data for evaluation presences but different data for evaluation pseudo-absences ?
Unfortunately, that is not directly handled by `biomod2`.
You can however do it yourself using `BIOMOD_FormatingData` to generate 30 pseudo-absence dataset for your evaluation data and then using `bm_FindOptimStat` to calculate your evaluation metric for each one of the evaluation dataset. I can share a small example script if you need.
Best,
Rémi
