### ISSUE TITLE
Help with BIOMOD_EnsembleModeling - meanbyTSS vs meanbyROC

### ISSUE THREAD

**Issue by LindeNozomiLeo** [biomodhub/biomod2#294]
Hi,
I was wondering what exactly meanbyTSS and meanbyROC, as I get both back when plotting binary FutureEM. As you can see in the code I used, I set the binary.metric as TSS, however, I still get both figures. 
I mostly want to know if in both versions all the models with an TSS<0.5 and AUC<0.7 are removed (as I put in the code for the ensemble modeling) and what the difference is between the maps, as it is not the metric used to create binary maps

**Code used**
Please add the code used here to illustrate your question. Start with `BIOMOD_FormatingData` up to the function on which you have questions. Please add as well the output of `show` for the different object used or generated. 

```
myBiomodModelOut<- BIOMOD_Modeling(bm.format=myBiomodData,
                                   models=c('GLM','GAM','RF','MAXENT'),
                                   bm.options=myBiomodOptions,
                                   var.import=3, 
                                   metric.eval= c('TSS','ROC'),
                                   CV.strategy = 'random', 
                                   CV.nb.rep = 3, 
                                   CV.perc = 0.75, 
                                   prevalence = 0.5, 
                                   nb.cpu = 12) 

myBiomodEM <- BIOMOD_EnsembleModeling(myBiomodModelOut,
                                      models.chosen = c("all"),
                                      em.by = 'all', 
                                      em.algo= c("EMmean"), 
                                      metric.eval = c("TSS","ROC"), 
                                      metric.select = c("TSS","ROC"),
                                      metric.select.thresh = c(0.5,0.7), 
                                      var.import = 2, 
                                      nb.cpu =12

for (scen in proj_scen) {
  cat("\n> projections of ", scen) 
  
  
  FutureEM<-BIOMOD_EnsembleForecasting(
    bm.em=myBiomodEMall,
    #bm.proj = myBiomodEMProj,
    proj.name = paste0('FutureEM_', scen),
    new.env = get(paste0("stk_", scen)),
    new.env.xy = NULL,
    selected.models = "all",
    metric.binary  = 'TSS',
    nb.cpu = 20,
  )
  
  pdf(paste0("Graphic_FutureEM_AB_", scen, ".pdf")) #pdf or png?
  plot(FutureEM)
  dev.off()
  
  pdf(paste0("Graphicbinary_FutureEM_AB_", scen, ".pdf"))
  plot(FutureEM, metric.binary="TSS")
  dev.off()
  
  # Load current and future binary projections per scen
  CurrentProjEM <- get_predictions(myBiomodEMProj, metric.binary = "TSS")
  FutureProjEM <- get_predictions(FutureEM, metric.binary = "TSS")
  
  # Compute differences per scen
  myBiomodRangeSizeEM <- BIOMOD_RangeSize(proj.current = CurrentProjEM, 
                                          proj.future = FutureProjEM)
  
  rangeEM_comp <- myBiomodRangeSizeEM$Compt.By.Models
  rangeEM_map <- myBiomodRangeSizeEM$Diff.By.Pixel
  writeRaster(rangeEM_map, filename = paste0("rangeEM_map_AB_", scen, ".tif"))
  write.table(rangeEM_comp, file = paste0("rangeEM_comp_AB_", scen, ".tif"))
  write.csv(rangeEM_comp, file = paste0("rangeEM_comp_AB_", scen, ".csv"))
  
  pdf(paste0("Graphic_RangeEM_AB_", scen, ".pdf"))
  plot(rangeEM_map)
  dev.off()
}


```

<img width="885" alt="Screenshot 2023-07-04 at 16 00 45" src="https://github.com/biomodhub/biomod2/assets/136846457/badaea3a-1325-4349-a40e-f434be55d021">

**Comment by rpatin** [comment]
Hi @LindeNozomiLeo,
Thank you for reporting :pray: 
Arguments \metric.eval` in `BIOMOD_EnsembleModeling` is a method to automatically filter the model used for ensembling according to `metric.eval.thresh`. The way it works when you give `metric.eval = c("ROC","TSS")` is by building two sets of ensemble models:
1. One set filtered by `ROC`, and called `byROC`. Only models with `AUC>0.7` are kept (no matter the `TSS`).
2. One set filtered by `TSS`, and called `byTSS`. Only models with `TSS>0.5` are kept (no matter the `AUC`).
Those metric may further be used by the ensemble algorithm (for weighted mean - `EMwmean`), it is why we do it like this.
The maps are thus different because the ensemble models behind them are different and based on different subset of models.

If you want to have a single Ensemble Model, filtered jointly by `AUC` and `TSS` you have to do it yourself, using the outputs of `get_evaluations` and providing `models.chosen` to `BIOMOD_EnsembleModeling`:
```
library(tidyr)
library(dplyr)
myModelSelection <- 
  get_evaluations(myBiomodModelOut) %>% 
  select(full.name, PA, run, algo, validation, metric.eval) %>% 
  pivot_wider(names_from = "metric.eval", values_from = validation) %>% 
  filter(TSS > 0.5, ROC > 0.7) %>% 
  pull(full.name)

myBiomodEM <- BIOMOD_EnsembleModeling(myBiomodModelOut,
                                      models.chosen = myModelSelection,
                                      em.by = 'all', 
                                      em.algo= c("EMmean"), 
                                      metric.eval = c("TSS","ROC"), 
                                      metric.select = "TSS",
                                      var.import = 2, 
                                      nb.cpu =12)
```

Note that the model will still by called `byTSS` although as we did not provide any `metric.select.thresh` all models are kept (given the one you provided in myModelSelection), as said by the message that you should get:
```
 ! No metric.select.thresh -> All models will be kept for Ensemble Modeling
```

Best regards,
Rémi
