### ISSUE TITLE
Which data set is more focused to select best algorithm in BIOMOD_models.out: Calibration or validation in the absence of evaluation?

### ISSUE THREAD

**Issue by mula-jpg** [biomodhub/biomod2#317]
Which data set is more focused to select best algorithm in BIOMOD_models.out: Calibration or validation in the absence of evaluation?

**Comment by rpatin** [comment]
Dear @mula-jpg,
Thank you for reporting :pray: 
I will answer to the question in the title:
> Which data set is more focused to select best algorithm in BIOMOD_models.out: Calibration or validation in the absence of evaluation?

Briefly, the validation dataset is more appropriate to select the best algorithm. In general looking at evaluation metric on the calibration dataset can be highly biased when some models can be prone to overfit. Looking at the validation dataset is more robust as it was not used to fit the model and provide some kind of external evaluation. I say some kind as it can share the same data structure as the calibration dataset (auto-correlation, distribution of environmental variables) and thus suffer from the same bias.

Please let us know if something is unclear or if you need additional information.

Best,
Rémi

**Comment by mula-jpg** [comment]
Dear Remi,
Thank you for your fast response, but can I get a reference for this idea to read more. Again, as you said, RF in calibration shows TSS = 0.9 but it is below 0.5 in validation in my project. Its ROC is above 0.8. Can I decide to remove this algorithm?

**Comment by rpatin** [comment]
Dear @mula-jpg,
Sorry I do not have specific references in mind for that. I'll try to discuss this with my colleagues. 
When `RF` calibration shows `TSS = 0.9` but is below 0.5 (and likely below other models) for the validation it is a clear sign of `RF` overfit. You can either remove it or try to tune its parameter to have better performance (there have been several discussion on that topic). The ROC is higher because the metric is threshold-independant.

Best,
Rémi

**Comment by mula-jpg** [comment]
Thank you very very much. I will tune before automatic removing.
