### ISSUE TITLE
response.plot3() crashes RStudio

### ISSUE THREAD

**Issue by REcologist** [biomodhub/biomod2#33]
**0. Session information**

```
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)
```

**1. Summary of my issue**

I am having a crash while using a modified function of `response.plot2()`, named `response.plot3()`. The problem is not the function in itself, as the same problem occurs with `response.plot2()`. 

![image](https://user-images.githubusercontent.com/84527320/119011834-b867ad00-b995-11eb-8b0a-26d2bf460f94.png)

**2. Code** 

```
library(biomod2)
library(raster)
library(reshape)
library(ggplot2)

setwd("xxx")

# I load the modified version of response.plot2()
source("/response.plot_modified.R", local = TRUE)

sp <- "NAME"
baseline_EU <- readRDS("./data/baseline_EU.rds")

initial.wd <- getwd()
setwd("models") 

# Loading of formatted data and models calibrated by biomod
load(paste0(sp, "/run.data"))
load(paste0(sp, "/model.runs"))

# Variables used for calibration
cur.vars <- model.runs@expl.var.names
  
# Loading model names into R memory
models.to.plot <- BIOMOD_LoadModels(model.runs)
 
# Calculation of response curves with all models (stored in the object resp which is an array)
resp <- response.plot3(models = models.to.plot,
                         Data = baseline_EU[[cur.vars]],
                         fixed.var.metric = "sp.mean",
                         show.variables = cur.vars,
                         run.data = run.data)
```

I have got 60 models and the code plot the first curve before aborting the session, with no further explanation.

**3. What I unsuccessfully tried**

(1) check that it was not a ram issue
(2) uninstall-reinstall all the packages and their dependencies
(3) uptade to the last R version
(4) go back to `response.plot2()` to see if the issue could come from `response.plot3()`

**4. I found some similar errors which lead me to think that it might be a package issue**

https://github.com/rstudio/rstudio/issues/9373
https://stackoverflow.com/questions/61599090/call-to-libraryraster-or-requireraster-causes-rstudio-to-abort-session

Now I presume that there is a problem either with the biomod2 or the raster packages, or maybe the R version?

I would greatly appreciate your help, this is my first time using github so my apologies if the question does not fit the standards of how a question should be asked.

**Comment by Farewe** [comment]
Hello there,

For context, I wrote the response.plot3() function, which is basically a fork from the response.plot2() function from ~2015 or 2016 iirc. This function was designed to add another possibility to the `fixed.var.metric` argument, where instead of fixing variables to an average over the entire study area, they are fixed to an average over species recorded presences. One day I'll propose a pull request to implement it properly in biomod2...

I have tested this function as of today, with R version 4.1.0 Rstudio  1.4.1717 and the github version of biomod2. It works properly.
`response.plot2()` also works properly here.

So, my best guess is that this is not an issue related to biomod2. 

Suggestions:

(1) Have you installed the development version of biomod2? If not, install it with `devtools::install_github('biomodhub/biomod2', dependencies = TRUE)`
(2) Check your raster temporary directory (`rasterOptions()`), just in case it is filled with temporary files which were not deleted. Delete everything inside if it's filled.
(3) Make sure your working directory is *short*. If your working directory is something long like e.g. `c:/users/fsqfsq/my documents/my project/project2/sdm models/`, then there is a very high probability that biomod2, when writing files on the hard drive, reaches the maximum path length of *255 characters* on Windows. Use a shorter working directory such as `c:/r/projectX`
(4) Next, I would probably investigate other issues unrelated with R/Rstudio/biomod2, such as the event observer in Windows to see what was triggered at the precise moment when rstudio crashes. But this issue tracker is not the place for such troubleshooting!

Cheers
Boris

**Comment by Farewe** [comment]
This issue should be closed I think.
 `response.plot2()` does now implement the possibility to fix metrics at the species presence points. Therefore, there is no more need for an externally modified version of this function.
@REcologist, see if the new version of `response.plot2()` works properly for you, and if it does not, then maybe reopen the issue.
