### ISSUE TITLE
Could you tell me how to use different pseudo-absence points for each algorithm in the latest version of Biomod2?

### ISSUE THREAD

**Issue by ReisDO** [biomodhub/biomod2#354]
Hello, I'm trying to carry out a modeling process and the methodology I'm following says that I must use different amounts of pseudo-absence for each algorithm (e.g. Random Forest must have 150 pseudo-absence points and GAM 10,000). Assuming that I want to create a consensus model from these different algorithms, how can I do this in Biomod2?

**Comment by MayaGueguen** [comment]
Hello there,

Multiple pseudo-absences sets can be used in `biomod2` through the [BIOMOD_FormatingData](https://biomodhub.github.io/biomod2/reference/BIOMOD_FormatingData.html) function by giving a `vector` of values instead of one single value to the `PA.nb.absences` parameter.
You can also check the [main](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html) and [secundary](https://biomodhub.github.io/biomod2/articles/examples_2_secundaryFunctions.html) examples pages about that.

Then, different sets of pseudo-absences can be attributed to each single model in the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function through the `models.pa` parameter.

For example : 
```
      myBiomodData <-
        BIOMOD_FormatingData(
          resp.var = myResp,
          expl.var = myExpl,
          resp.xy = myRespXY,
          resp.name = myRespName,
          PA.nb.rep = 4,
          PA.nb.absences = c(1000, 500, 500, 200),      ## <===
          PA.strategy = 'random')
      
      myBiomodModelOut <-
        BIOMOD_Modeling(
          bm.format = myBiomodData,
          modeling.id = 'test',
          models = c('RF', 'GLM', 'MARS'),
          models.pa = list(RF = c("PA1", "PA2"), GLM = "PA3", MARS = c("PA2", "PA4")),   ## <===
          CV.strategy = 'random',
          CV.nb.rep = 2,
          CV.perc = 0.8,
          OPT.strategy = 'default',
          var.import = 2,
          metric.eval = c('TSS','ROC'),
          seed.val = 42
        )
```

Hope it helps,

Maya

**Comment by ReisDO** [comment]
Thank you so much for your assistance!
