### ISSUE TITLE
Error in BIOMOD_Modeling - (variable lengths differ) and (object 'model.bm' not found)

### ISSUE THREAD

**Issue by Data-Madman** [biomodhub/biomod2#362]
Hellow everyone,

I get an error when running the function "BIOMOD_Modeling".
Codes:
```
myBiomodModelOut <- BIOMOD_Modeling(
  data= myBiomodData, #Formated imput data
  models =  c("MAXENT", "RF", "GLM"),
  models.options = myBiomodOptions, # Call the options defined in the previous steep
  NbRunEval= 10,      # Number of Evaluation run (number of cross validations in output as RUN1,RUN2, etc.)
  DataSplit=70,     # % of data used to calibrate the models, the remaining part will be used for testing
  Prevalence=NULL,   # either NULL (default) or a 0-1 numeric used to build 'weighted response weights'
  VarImport=1,      # Number of permutation to estimate variable importance
  models.eval.meth = c("ROC", "TSS"), #vector of names of evaluation metric
  SaveObj = TRUE,    #keep all results and outputs on hard drive
  rescal.all.models = F,# if true, all model prediction will be scaled with a binomial GLM
  do.full.models = F, # uses all data for training, and then evaluates with the same!!, not recomended
  modeling.id = paste(myRespName,"Littorina_models",sep=""))##name that the output will have

```
For example:
```
Model=Generalised Boosting Regression 
	 2500 maximum different trees and  3  Fold Cross-Validation
	> GBM modeling...Error in model.frame.default(formula = bm_MakeFormula(resp.name = resp_name,  : 
  变数的长度不一样('Present.Surface.Temperature.Max')
Error in h(simpleError(msg, call)) : 
  在为'predict'函数选择方法时评估'object'参数出了错: object 'model.bm' not found 
```
I use the Chinese version of the R. The error message translated should be:
```
Model=Generalised Boosting Regression 
	 2500 maximum different trees and  3  Fold Cross-Validation
	> GBM modeling...Error in model.frame.default(formula = bm_MakeFormula(resp.name = resp_name,  : 
  variable lengths differ('Present.Surface.Temperature.Max')
Error in h(simpleError(msg, call)) : 
 Error in evaluating 'object' argument when selecting a method for 'predict' function: object 'model.bm' not found" would be: "Error in eval(predvars, data, env) : object 'model.bm' not found
```
I tried deleting variables such as "'Present.Surface.Temperature.Max" until I got to the point where there was only one variable, and the error remained unchanged.

So I'm very troubled.
I'm not sure if this has anything to do with the input data. I used environmental data from the intertidal zone.
![image](https://github.com/biomodhub/biomod2/assets/81616267/eddf2bcc-1d3e-447a-8a1a-20e522ba8654)

However, the function had run successfully when I used worldclim and some of the environmental data provided directly by the marine database.
![image](https://github.com/biomodhub/biomod2/assets/81616267/1fd122f3-cd6b-467e-b2a8-5a2dfbc9ba57)

I didn't find any information on variable length inequality. I am sure that all my variables have the same length.

Thank everyone，
Linxuan

**Comment by MayaGueguen** [comment]
Hello Linxuan,

Thank you for your detailed issue :pray: 

First, it seems that you are using a quite old version of `biomod2` so I will not be able to fully help you as a lot of things have changed since then...
I strongly advise you to try and install at least the last CRAN version (4.2-4) through the `install.packages` function. A lot of parameter names changed, as well as some functions behavior, but we try to keep an up-to-date documentation on [our website](https://biomodhub.github.io/biomod2/index.html) as well as [fully detailed examples](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html).
And of course I'm here to help if you have any questions through this translation process.

Second, in general, try not to have `.` (dots) within your variable names. It may cause trouble sometimes to some models to deal with it. Try and replace them with `_` (underscore) for example.

Hope it helps,
Maya

**Comment by Data-Madman** [comment]
Hi Maya,

Thank you very much for your answer. I managed to run the code successfully by updating biomod2 to 4.2-5.

Linxuan
