### ISSUE TITLE
RF TSS values differ strongly between versions

### ISSUE THREAD

**Issue by JotDotW** [biomodhub/biomod2#369]
Dear Biomod Team

I am a long year user of biomod. First of all, thanks for the nice package ;)

I just got back the revision of a manuscript were I used biomod. Therefore, I had to rerun the models. 
As the original runs happened quite a while back (biomod2 version 3.3-7.1) and I now have a newer version on the server I am using, I simply updated the code to the newest version (4.2-4) and reran all species

When I compared the TSS values of the single models of the two versions, I realised that the TSS values of RF suddenly dropped. For all other algorithms they are kind of in the same range, so no problem there.

I used default settings of biomod, and as far as I read they did not change. 
so, do you have any idea what the reason here is?

I now setup the old version on the server again and the TSS values are in range again, so this is not a random event
Looking at it in more detail, I realised that there is a strong drop between the TSS values of the calibration data and the validation data (in the new version) for RF. This looks like overfitting, but I wonder why this was not the case before

finally, I checked this with many outputs from the new biomod version, and it seems that this is an overall pattern (I checked it for my 70 species, and for many more)
what I want to say: I can send you the species data so you can reproduce this, but I think this should happen with any dataset you use

here are the TSS values for one species:

biomod 3.3-7.1
"RUN1","RUN2","RUN3"
"GLM",0.563,0.55,0.549
"GAM",0.582,0.577,0.576
"RF",0.618,0.596,0.608
"GBM",0.616,0.607,0.604

biomod 4.2-4
"RUN1","RUN2","RUN3"
"GLM",0.558,0.57,0.552
"GAM",0.575,0.593,0.572
"RF",0.392,0.378,0.395
"GBM",0.612,0.612,0.588

here is the old and new code:
biomod 3.3-7.1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
myBiomodData <- BIOMOD_FormatingData(resp.var       = myResp,
                                       expl.var       = myExpl_input,
                                       resp.xy        = myRespCoord,
                                       resp.name      = myRespName,
                                       na.rm          = TRUE)
  
  
  
  #############################################
  #### 2. Define Modelingoptions ##############
  #############################################
  
  modelset            = c("GLM","GAM","RF", "GBM")
  ## use default settings:
  myBiomodOption <- BIOMOD_ModelingOptions()
  
  
  
  #############################################
  #### 3. SDM Calibration #####################
  #############################################
  
  
  
  myBiomodModelOut <- BIOMOD_Modeling(myBiomodData, 
                                      models            = modelset,
                                      models.options    = myBiomodOption, 
                                      NbRunEval         = 3, 
                                      DataSplit         = 70,
                                      Prevalence        = 0.5, 
                                      VarImport         = 3, 
                                      models.eval.meth  = c("TSS", "ROC", "KAPPA"),
                                      SaveObj           = T, 
                                      rescal.all.models = T, 
                                      do.full.models    = F,
                                      modeling.id       = myRespName )

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

biomod 4.2-4
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

  myBiomodData <- BIOMOD_FormatingData(resp.var       = myResp,
                                       expl.var       = myExpl_input,
                                       resp.xy        = myRespCoord,
                                       resp.name      = myRespName,
                                       na.rm          = TRUE)
  
  
  
  #############################################
  #### 2. Define Modelingoptions ##############
  #############################################
  
  modelset            = c("GLM","GAM","RF", "GBM")
  ## use default settings:
  myBiomodOption <- BIOMOD_ModelingOptions()
  
  
  print("1 done")
  #############################################
  #### 3. SDM Calibration #####################
  #############################################
  
  
  
  myBiomodModelOut <-  BIOMOD_Modeling(bm.format = myBiomodData,
                                    models = modelset, 
                                    bm.options = myBiomodOption,
                                    CV.strategy = "random",
                                    CV.nb.rep = 3,
                                    CV.perc = 0.70, 
                                    var.import = 3,
                                    metric.eval = c("KAPPA", "TSS", "ROC"),
                                    CV.do.full.models = FALSE,
                                    scale.models = T)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

thanks a lot in advance
all the best
johannes

**Comment by MayaGueguen** [comment]
Hello Johannes,

Thank you for this comparison :pray: :eyes: 

There has been quite a lot of changes between versions `3.3-7-1` and `4.2-4`.

First in terms of global organization (function names, parameter names), but also a lot of code cleaning and improvement.
Default parameterization did not change indeed, but we added some parameters sometimes (for example `do.classif` and `sampsize` parameters for RF #297).

We also checked and reorganized the data upon which evaluation metrics were effectively calculated and rendered. If I'm remembering right, in previous versions, only one value was returned for evaluation metric, calculated on _validation_ dataset. Now we return values both for _calibration_ and _validation_ dataset. But sometimes this single evaluation value was not exactly computed on the correct calibration / validation lines I think...

In general, I would be more confident with evaluation values calculated with the last versions rather than the `3.3[...]` versions.
As for these specific differences for `RF`, this is a remark that we already had, often linked with the fact that `RF` is overfitted on _calibration_ data and then doing worse on _validation_ dataset. So I advise you strongly to check `randomForest` parameters, especially `nodesize` parameter for example (see https://github.com/biomodhub/biomod2/issues/261#issuecomment-1598798884). And also, we are not aware of changes that might have occurred in the [randomForest](https://cran.r-project.org/web/packages/randomForest/index.html) package itself.

Hope it helps,
Maya
