### ISSUE TITLE
Question about using TSS for binary transformation

### ISSUE THREAD

**Issue by EllieHarris-1** [biomodhub/biomod2#406]
When projecting a model and setting ```metric.binary = 'TSS'```,  I am under the impression that the threshold is set at the value that maximises the TSS score for that model. How can I see the exact value it has used for this threshold?

Also, if I have an ensemble with 5 models projected to a new environment, and a separate TSS threshold is calculated for each model how are these combined into the final binary ensemble output?

Any further explanation would be greatly appreciated. Thank you!

```
myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM,
proj.name = 'CurrentEM',
new.env = myExpl,
models.chosen = 'all',
metric.binary = 'TSS')

```

**Comment by MayaGueguen** [comment]
Hello Ellie,

Yes, the threshold used to transform probability values into binary is the one which optimises the evaluation metric selected, TSS here. The value is provided for each model within the evaluation table that you can retrieve with the [get_evaluations](https://biomodhub.github.io/biomod2/reference/getters.out.html) function, giving it your output of the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or the [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions.
:warning: _keep in mind that this threshold, as well as probability values, might be given on a scale between `0` and `1000` rather than `0` and `1`_

As for ensemble modeling, you have to think it a bit differently.
_Let's say that you want to combine your 5 single models using the probability weighted mean method (`em.algo = 'EMwmean'` within [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) function)._
- the 5 predictions of probabilities will be averaged together, each model weighted by its TSS value
- this will give 1 new map of probabilities, and this map will be used to calculate a new threshold to optimize the TSS value comparing these new probabilities to observations
- again, you can retrieve these informations with the [get_evaluations](https://biomodhub.github.io/biomod2/reference/getters.out.html) function, giving it your output of the [BIOMOD_EnsembleModeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) function

Hope it is clearer that way, do not hesitate if you have more interrogations :eyes: 

Maya

**Comment by EllieHarris-1** [comment]
Thanks very much for your response - this all makes sense to me now!

Ellie
