### ISSUE TITLE
Biomod projection for Climate Change

### ISSUE THREAD

**Issue by ShreePoudel0** [biomodhub/biomod2#451]
hello, I am doing a habitat suitability projection under different Climate Change Scenarios. i have downloaded future CC models from bioclim website and i don't quite understand how this function works. For the current projection, I have used bioclim data set as well as anthropogenic variables. Since we dont have future data for those anthropogenic variables, do we stack only the future Climatic variables or future climatic variables and current anthropogenic variable. 
I tried doing with the later and I had unsatisfactory result. 
![Screenshot 2024-05-05 123115](https://github.com/biomodhub/biomod2/assets/140482710/a3fb296a-9244-4842-a541-779a4cc350b7)
I have added a screenshot of current projection. Here the value ranges upto 800 but when doing future projection the value is just upto 400 and the result is very unsatisfactory. Do we have some way to make this uniform.

The code I use is given below:
myBiomodProj <- BIOMOD_Projection(bm.mod = myBiomodModelOut,
                                  proj.name = 'Current',
                                  new.env = myExpl2040,
                                  models.chosen = 'all',
                                  metric.binary = 'all',
                                  metric.filter = 'all',
                                  build.clamping.mask = F)

myBiomodEMProj <- BIOMOD_EnsembleForecasting(bm.em = myBiomodEM, 
                                             proj.name = 'try',
                                             new.env = myExpl2040,
                                             models.chosen = 'all',
                                             metric.binary = 'all',
                                             metric.filter = 'all')

**Comment by HeleneBlt** [comment]
Hello there ! 

If you don't have all the predictions for your variables, you have two options : 

- You can assume the anthropogenic variables don't change and you add the current anthropogenic variables to the future climatic variables (this is what you're already doing)
- You build a model with the climatic variables only and you project it with the future climatic variables.

Be careful with the result of `Biomod_EnsembleForcasting` : be sure which EM you're looking at. For example, EMmean and EMcv will not have the same range because they don't represent the same thing. 

If it doesn't help, please don't hesitate to let us know more about your case so we can help you.
Hélène

**Comment by ShreePoudel0** [comment]
Hello again.
Is it better to stack new expl variable and use it directly in
EnsembleForecasting with new.env or we can altogether start the process
from biomodFormatting using new future explanatory variable.
Thank You

**Comment by HeleneBlt** [comment]
Hello Shree,

If you stack your new expl variables and use them directly in `BIOMOD_EnsembleForecasting`, the projection will be created with your Ensemble Model created with your initial expl variables. (That's why you can add a new variable and you have to keep the same names.)
If you restart the process from `BIOMOD_Formating`, you will create a new model based on these new variables. 
So it depends on what you want. 

Hope it's clearer, 
Hélène
