### ISSUE TITLE
Habitat suitability, is there any unit ?

### ISSUE THREAD

**Issue by lpittet92** [biomodhub/biomod2#463]
Hello,

My question is very simple. Is there any unit to the suitability scale used for projection ?

I have been thinking of this for a while and couldn't find any answer.

Thank you for the great platform !

All the best,

Loic

**Comment by MayaGueguen** [comment]
Hello Loïc 👋 

Predictions are by default rendered between `0` and `1000`. Why ? Simply because it is lighter to save _integer_ values rather than _decimal_ values. And if you want to use several algorithms, with several pseudo-absence datasets, etc, number of models and then predictions quickly increase. So we multiply predictions by `1000` but there are still to be seen as probabilities 🙂 

If this is too counter-intuitive for you, or if you don't have memory concerns, or you don't want to have to divide predictions by `1000`, or simply you prefer it that way ! there is a parameter within [BIOMOD_Projection](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) and [BIOMOD_EnsembleForecasting](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions allowing to control for this : `on_0_1000`. It is set by default to `TRUE` and you can change it to `FALSE` to have directly predictions between `0` and `1`.

Hope it helps,
Maya
