### ISSUE TITLE
Question about tuning Maxent

### ISSUE THREAD

**Issue by ls320** [biomodhub/biomod2#516]
Hello, 
I am trying to tune Maxent model but not sure how it should be done. In my code below I specifyed a 5-fold cv in BIOMOD_modeling, but the the message said a 10-fold cv is used. I would like to know how  is the traing done in this process? Which cv setting is used?

Also I didn't provide the range of model parameters to be tuned but the code can still run. Does it mean the model was not tuned or there is a default setting? 

Thank you very much

### code
```
data=BIOMOD_FormatingData(resp.name = 'SP1',resp.var=data_final$pr_ab,expl.var=data_final[c("wc2.1_2.5m_bio_1",'wc2.1_2.5m_bio_8')], PA.strategy='user.defined',
                            resp.xy=vd_final[c('lon','lat')], PA.user.table=sp_pseudo_table,PA.nb.rep=5)
model_output=BIOMOD_Modeling(data,models=c('MAXENT'),CV.strategy = 'kfold',
                             CV.nb.rep=1,CV.k=5,var.import=100,OPT.strategy='tuned')
```

### message of BIOMOD_Modeling
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...

	> Automatic weights creation to rise a 0.5 prevalence
Creating suitable Workdir...


Checking Cross-Validation arguments...

   > k-fold cross-validation selection

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Modeling Options -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

	>  MAXENT options (datatype: binary , package: MAXENT , function: MAXENT )...
 No optimization of formula for MAXENT
		> Dataset _PA1_RUN1
			> Tuning parameters...Package ecospat is not installed, so Continuous Boyce Index (CBI) cannot be calculated.
*** Running initial checks... ***

* Variable values were input along with coordinates and not as raster data, so no raster predictions can be generated and AICc is calculated with background data for Maxent models.
* Model evaluations with random 10-fold cross validation...

*** Running ENMeval v2.0.4 with maxnet from maxnet package v0.1.4 ***

  |                                                                            |   0%
```

**Comment by MayaGueguen** [comment]
Hello there :wave: 

Maxent tuning is a bit specific and is done through the [ENMevaluate](https://www.rdocumentation.org/packages/ENMeval/versions/0.3.1/topics/ENMevaluate) function from [ENMeval](https://jamiemkass.github.io/ENMeval/articles/ENMeval-2.0-vignette.html#) package.

We set up `partitions = "randomkfold"` and `partition.settings = list(kfolds = 10)`, which explains why you see the message : 

>  Model evaluations with random 10-fold cross validation...

It will apply this random cross-validation over each of your PA x CV datasets.
So here you have 5 pseudo-absence datasets x 5 kfold datasets = 25 models to be run, and for which tuning will be computed for each run.

Otherwise, yes, you cannot change by yourself the tuned parameters, which are set to : `tune.args = list(rm = seq(0.5, 1, 0.5), fc = c("L"))`. If you want to be more specific in your tuning, please use directly by yourself the ENMevaluate function, and then provide your tuned parameter values to biomod2 functions using the `OPT.strategy = "user.defined"` option.

:eyes: _I see that you put `var.import = 100`, I suggest you to put that to 10 only or it will take waaaaaaaaay too long._

Hope it helps,
Maya

**Comment by ls320** [comment]
Maya, Thank you for your explantion and advice! Does it mean that for each run, a 10 fold cv is first applied on the traing folds to tune the model? or it is applied on the whole traing+validation folds?

Thanks

**Comment by ls320** [comment]
Maya, Thank you for your explantion and advice! Does it mean that for each run, a 10 fold cv by ENMevaluate is first applied on the traing folds I set to tune the model? or it is applied on the whole  traing+validation folds?

Thanks

**Comment by ls320** [comment]
Thank you for the further explanation
