### ISSUE TITLE
Interpretation of the boxplots from BIOMOD_CrossValidation

### ISSUE THREAD

**Issue by luispedrosantiago** [biomodhub/biomod2#63]
Hi Maya,

I read somewhere that the size of the gap between cross-validation methods of the same model would indicate whether there was either model underfitting (large gap), or overfitting (no gap). However, I do not know how to interpret this. Is underfitting/overfitting reflected by the gap between boxplots, or medians? Or am I saying something completely wrong?

Best,

Luís

**Comment by MayaGueguen** [comment]
Hello Luis,

I'm sorry but I'm not sure I'm getting what you mean..
Could you maybe send me a boxplot graphic :framed_picture: with your interpretation, and I'll tell you my point of view ? :eyes: 

Maya

**Comment by luispedrosantiago** [comment]
Hi Maya,

Of course, sorry if I was not very understandable.
For instance when running your [example](https://biomodhub.github.io/biomod2/reference/BIOMOD_CrossValidation.html) for Cross Validation, I get the boxplots attached
![cv](https://user-images.githubusercontent.com/74597149/169283001-c7840eb5-8f22-4acd-9634-57c947c2c1b9.JPG)

My question is: what do you make of them, or how I can interpret them in this context?

Luís

**Comment by MayaGueguen** [comment]
Hello Luis,

Thak you for the precisions :pray: 

Here are some interpretations I would give from this plot : 

- the wider the boxplot is (_big range between min and max values, like the one on the right_), the less robust your model is. It means that, depending on the data you've selected to train your model with, you can as well get good predictions (_with TSS around 0.8_) as bad ones (_with TSS close to 0_)
- on the contrary, a boxplot with small extent in values will mean that your model is consistent, no matter which part of your dataset you are using to train it

+ you will most likely get the best score values when using all your dataset, since you will give more informations to the model (_boxplot on the left_)

Here are some things to keep in mind : 

- you are only seeing here scores calculated over TEST dataset, and not the values obtained from the TRAINING datasets
- if you had both, you could compare the TSS values (_which is often nice, I will add this to my todo list :ballot_box_with_check:_)
- but from you're looking at right now, you cannot deduce things about over/under fitting

Hope it helps
Maya
