### ISSUE TITLE
Questions about follow-up mapping

### ISSUE THREAD

**Issue by 675979649** [biomodhub/biomod2#64]
Hi , Maya:
  With the biomod2 package we get the prediction results of different models, but how can these results be imported into ArcGIS for mapping? Maybe I didn't find the right way, when I import the gri file it will report an error.
Best wishes,
Weicheng Ding

**Comment by MayaGueguen** [comment]
Hello Weicheng Ding,

Prediction maps can be created either with the [`BIOMOD_Projection`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) (for single models) or [`BIOMOD_EnsembleForecasting`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) (for ensemble models) functions. When calling these functions, you can specify the output.format parameter which can be `.grd`, `.img` (if you gave a RasterStack to `new.env`) or `.RData`.
I'm not :100: % familiar with ArcGis... but maybe you should try opening the `.grd` file instead of the `.gri` ?

Hope it helps
Maya

**Comment by kjirsten-c** [comment]
> Hello Weicheng Ding, I tried it out and with the .grd file (in my case a binary map output from the Ensemble Model) you will need then to configure the Symbology. You might see that there are 4 bands (Red, Green, Blue and Alpha). I was able to project a binary map when I configured the Red as one of the selected EM (example EM_wmean) and "Display background value" as Red = 1 in e.g. green color. QGIS might be a possibility too since the file type .grd is native to the software. However, I neither can't do any further calculations with the raster... :( No ArcGIS, no QGIS Did you find another better solution?
> 
> ![arcmap_grd](https://user-images.githubusercontent.com/52442108/171454447-ecaf606d-9b3f-4957-b173-dab088dbd9f1.jpg)

Hi Cam-in, I am still unclear about how you exported your binary projection from R to be used in QGIS. Could you explain or provide some script? Thanks!

Kjirsten

**Comment by 675979649** [comment]
> Hello Weicheng Ding, I tried it out and with the .grd file (in my case a binary map output from the Ensemble Model) you will need then to configure the Symbology. You might see that there are 4 bands (Red, Green, Blue and Alpha). I was able to project a binary map when I configured the Red as one of the selected EM (example EM_wmean) and "Display background value" as Red = 1 in e.g. green color. QGIS might be a possibility too since the file type .grd is native to the software. However, I neither can't do any further calculations with the raster... :( No ArcGIS, no QGIS Did you find another better solution?
> 
> ![arcmap_grd](https://user-images.githubusercontent.com/52442108/171454447-ecaf606d-9b3f-4957-b173-dab088dbd9f1.jpg)

Hi Cam-in, I'm sorry for the delay in replying. I don't have a good way to export raster either. Maybe try a new version of the model ? If we can solve it, we hope to share the method here.

**Comment by MayaGueguen** [comment]
Hello Cam-in and Weicheng,

Sorry for the trouble caused by the `.grd` format, it seems not straightforward to open it with GIS tools such like ArcGis or QGis... 
But what you can try, is to open the `.grd` file within R, and then resave it into another format, better understood by the softwares. For example : 
```
library(raster)
stk = stack("yourmodelprojection.grd")
writeRaster(stk, filename = "yourmodelprojection.img")
```

Hope it helps,
Maya

**Comment by kjirsten-c** [comment]
Hi folks, 
I am creating a point model with my own background points, instead using rasters. So this is less straight-forward for me, but I have resolved a way to do this. It's actually quite simple. Just subset the myBiomodProj projection object. Because it's a data frame, you can just take the evaluation metric and the coordinates and create a new dataframe. Then load into QGIS as a csv and get to work with some clever symbology. Apologies for my simple code:

(Note I am exporting two models, one with RF and one with Maxent)

proj_coords = myBiomodProj1@coord
proj_coords = as.data.frame(proj_coords)

projection = myBiomodProj1@proj.out@val
projection = as.data.frame(projection)

proj_data = cbind(projection,proj_coords)
names(proj_data)

proj_data_RF = subset(proj_data, select = c("RF.RUN1.PA1", "long", "lat"))
proj_data_Max = proj_data[2:4]

#Define objects with CRS
LatLong <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"  # EPSG:4326

#Extract the coordinates
proj_data_RF <- data.frame(long = proj_data_RF$long, 
                             lat = proj_data_RF$lat, 
                             presence = proj_data_RF$RF.RUN1.PA1)

proj_data_Max <- data.frame(long = proj_data_Max$long, 
                                   lat = proj_data_Max$lat, 
                                   presence = proj_data_Max$MAXENT.Phillips.2.RUN1.PA1)

#Set spatial coordinates to create a Spatial object
coordinates(proj_data_RF) <- c("long", "lat")
coordinates(proj_data_Max) <- c("long", "lat")

#Assign a projection
proj4string(proj_data_RF) <- CRS(LatLong)
proj4string(proj_data_Max) <- CRS(LatLong)

write.csv(proj_data_RF, "proj_data_800m_grid_winter_DEM_RF.csv")
write.csv(proj_data_Max, "proj_data_800m_grid_winter_DEM_Max.csv")

##############################
#### END ####
##############################

Kjirsten
