### ISSUE TITLE
Computing time

### ISSUE THREAD

**Issue by Cam-in** [biomodhub/biomod2#66]
Dear Maya, Damien, Wilfried and all BIOMOD2 Team, 
thanks for the great job with version 4.0 and the compacted functions! 
Rdocumentation, it's btw lovely ♥

Curiosity cames up with my non-informatic background... What does the nb.cpu stands for in the optimization of run? How can I properly used? I have the idea biomod2 v4.0 is much faster when processing projections and ensemble model than v3.5.1. But I haven't yet exacltly played with same parametrization/data.
Could you give me a hint? And do we really know, average, how much faster is the process with new version? 

Thanks!
Best wishes, 
Cami Neder

**Comment by MayaGueguen** [comment]
Hello Cami,

Thank you so much for the positive feedbacks ! :pray: 
It is always nice to know that changes are well received :sun_with_face: , and not only causing problems :smile: 

As for your question about computation time, here are some answers, unfortunately not all very precise : 

- I cleaned up a lot `biomod2` functions, and tried to get rid of unecessary steps, or mutualize some, so that must be a good part of the "fastening" part :) 
- however, I'm sorry, I did not take time to try and compare speed of runs between 3.5.1 and 4.0 version...



As for the `nb.cpu` parameter : 
- it can be used within the following functions : 
   + [`bm_RunModelsLoop` and `bm_RunModel`](https://biomodhub.github.io/biomod2/reference/bm_RunModelsLoop.html) functions, which are called by the [`BIOMOD_Modeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) and [`BIOMOD_EnsembleModeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions (_so you can use it within these functions_)
   + [`BIOMOD_Projection`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Projection.html) functions, which is also called by the [`BIOMOD_EnsembleForecasting`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) functions (_so you can use it within these functions_)
- and it can parallelize the following actions (if used) : 
   + the single models computation
   + the projections

So, for example, if you have a computer with sufficient cores and RAM, you can set `nb.cpu = 2` (_or more if your machine supports it_), and calculations will be running "twice" faster (_might not divide exactly computation time by two, but you will have two models or projections running at the same time, so almost_).

Hope it helps
Maya

**Comment by Cam-in** [comment]
Super! Thanks Maya
I decided to use biomod v3.5.1 to not apply so many changes at the moment in the research. But the changes in biomod v4 are nice to test included if the arguments to fasten the results ;)
