### ISSUE TITLE
Getting familiar with biomod version 4 (Variable calculation, projection, binary transformation)

### ISSUE THREAD

**Issue by Cam-in** [biomodhub/biomod2#67]
I am restructuring my biomod2 analysis (version 3.5.1 into version 4.0) and I have some issues. I am not pretty sure if it is since I am wrong in the script or an actual bug:

1) When calculating variable importance i recieve the error that bm.model must be a 'biomod2_model' but the biomod model it is not recognized as one? Neither the Ensemble.
bm_VariablesImportance(bm.model = myBiomodModelOut, expl.var = myExpl,
                                                  method = "full_rand",
                                                  nb.rep = perm_number)

Further, how can a single EM output be selected for the calculations? example myBiomodEM@em.models$Mal.day_EMwmeanByTSS_mergedAlgo_mergedRun_mergedData@model  Otherwise for BoxPlot Variable Importance, all the EM output are modelled. 

2) In BIOMOD_Projection even when using argument output.format = '.img', files are not produced
 consequently, I can not plot Responses curves 

3) How can be the binary transformation applied for the EM? :  bm_BinaryTransformation(myBiomodEM, 0.6)

Thank you

**Comment by MayaGueguen** [comment]
Hello Cami,

Thank you for doing the effort to switch from 3.5.1 to 4.0 :)
And sorry if all is not straightforward within the new functions and documentation.

Here are some answers : 

1. Computation of variables' importance can be asked directly within the [`BIOMOD_Modeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [`BIOMOD_EnsembleModeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) by setting the `var.import` parameter to a value > 0 (_and corresponding to the number of replicates to compute for the variables importance_).
If you want to use directly the secundary function [`bm_VariablesImportance`](https://biomodhub.github.io/biomod2/reference/bm_VariablesImportance.html), it only runs for one model at a time, and then the `bm.model` parameter is not directly an output object obtained from the [`BIOMOD_Modeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [`BIOMOD_EnsembleModeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) functions, but rather a single model that might have been calculated by these previous functions.
For example, you run a set of single models with the [`BIOMOD_Modeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) functions and put it into the `bmOut` object. Then, to get one of the run model, you can use the [`get_built_models`](https://biomodhub.github.io/biomod2/reference/getters.out.html) function to get the names of the computed models (`nam = get_built_models(bmOut)`), and the [`get_formal_model`](https://biomodhub.github.io/biomod2/reference/getters.bm.html) function with one of the single model name (`bm_VariablesImportance(bm.model = nam[1], ...)`).

Tell me if this is still not clear for you, but hopefully, with functions help and examples, you might get how it is structured.

1. bis : Unfortunately, the [`bm_PlotVarImpBoxplot`](https://biomodhub.github.io/biomod2/reference/bm_PlotVarImpBoxplot.html) function only works with [`BIOMOD_Modeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) or [`BIOMOD_EnsembleModeling`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleModeling.html) outputs, so you cannot take only a subset of the models with run. But you can get values of variables importance with the [`get_variables_importance`](https://biomodhub.github.io/biomod2/reference/getters.out.html) and use it to create your own graphical representation.

2. What kind of data do you give to the `new.env` parameter ? If you give a table and not a `stack` object, then I don't think you can get raster output.

3. As for variables'importance, you can directly apply binary transformation to your ensemble models within the [`BIOMOD_EnsembleForecasting`](https://biomodhub.github.io/biomod2/reference/BIOMOD_EnsembleForecasting.html) function with the `metric.binary` parameter.
Otherwise, you can use the secundary function [`bm_BinaryTransformation`](https://biomodhub.github.io/biomod2/reference/bm_BinaryTransformation.html) but it does not work directly with `biomod2` output objects. You have to give directly a `vector` or `raster` of prediction values, that you can obtain from your projections.


Hope it helps,
Maya

**Comment by Cam-in** [comment]
Thank you Maya! 
I have to definitely try out. I am working with antarctic benthic species and raster environmental parameters, that's why I was expecting a stack output. And I was not familiar with the get_built_models since I was always working from the output as a stack. However, I get what you said. Gracias for that!

I stick to the previous biomod2 version at the moment. Did my own graphical representation for variables' importance, based on that function. Thanks bm_BinaryTransformation works with raster or vector was not clear for me in the documentation! 
Extra question, metric.binary = TSS produce the binary transformation for the Ensemble but can also be applied in the biomod_Projection for binary analysis in the single algorithms, isn't?

Have a nice day!
Cami
