### ISSUE TITLE
Problem selecting model parameters and algorithms 

### ISSUE THREAD

**Issue by pabloriul** [biomodhub/biomod2#91]
Dear Biomod Team,

Congratulations for the new version of Biomod2 its seems a great! I’m very happy with some of the changes and started to run some tests, so I’m writing you regarding some strange new behaviors like you said in the website. 

First I noticed is I can’t change the default modeling options with BIOMOD_ModelingOptions() as I used to do with the previous version. I tried in three different computers using macOS, ubuntu and windows and I cannot change model options, neither exclude any models (as shown in the print screen attached). It seems its always setting to defaults when I run the function. I also tried changing the name of my BIOMOD_ModelingOptions object and tried to manually change the parameters in the slots of the myBiomodOptions object unsuccessfully.

 A second thing I noticed is when I try to run BIOMOD_PresenceOnly I get an error related to biomod2 version (also attached).

Thank you very much for your attention,

Pablo Riul

<img width="1680" alt="myBiomodOptions" src="https://user-images.githubusercontent.com/7608824/186333880-5c62c631-c6ef-4b9f-a9f4-79f2f6affc65.png">
<img width="1680" alt="BIOMOD_PresenceOnly" src="https://user-images.githubusercontent.com/7608824/186334039-10db7641-2e04-4a15-848b-306ac16118fb.png">

**Comment by MayaGueguen** [comment]
Hello Pablo,

Thank you for your feedback, it is always appreciated :pray: 

Here are some answers to your questions : 

1. Not sure what you meant with the _default modeling options_...
To me, your screenshot is showing correct behavior, and I'm getting the same on my computer...
Here is the example : 
```
## Print DEFAULT options
bm_DefaultModelingOptions()

myBiomodOptions <- BIOMOD_ModelingOptions(
  GLM = list(type = 'simple',
             interaction.level = 0,
             myFormula = NULL,
             test = 'AIC',
             family = binomial(link = 'logit'),
             control = glm.control(epsilon = 1e-08,
                                   maxit = 50,
                                   trace = FALSE)))

## Print MODIFIED options
myBiomodOptions
```
GLM options are well changed between the two prints.
As for the question _about excluding models_, this is not done when defining the modeling options, but rather into the modeling in itself through the [BIOMOD_Modeling](https://biomodhub.github.io/biomod2/reference/BIOMOD_Modeling.html) function in itself and its `models` parameter. Hence, options for all models are always shown through the modeling options function, but it does not mean that all presented models will be used when running the models.


2. Concerning the `BIOMOD_PresenceOnly` function, I'm afraid I know the answer and it is a bit _messy_...
`BIOMOD_PresenceOnly` function depends on 2 functions from the [ecospat](https://github.com/ecospat/ecospat) package :  `ecospat.boyce` and `ecospat.mpa`. But this package also depends on some `biomod2` functions for some of its own functions. You see there is a dependency loop here, meaning that both packages need to be up to date concerning the other.
When updating the `biomod2` package to version 4.0, I did the corresponding changes into the `ecospat` package, and they were accepted. But since, they withdraw them, and went back to the former code... meaning that currently, `ecospat` package depends onto `biomod2` version 3.5. The dependency loop is flawned. This has to be changed. I'll try to take care of it as soon as possible.


Sorry for the inconvenience...
Maya

**Comment by pabloriul** [comment]
Dear Maya,

Thank you very much for your reply and sorry for the confusion regarding myBiomodOptions, I wrongly thought one would set the models using myBiomodOptions in addition to BIOMOD_Modeling. 

Cheers,

Pablo

**Comment by MayaGueguen** [comment]
Pablo,

I just made some updates to the github version : dependency from the `ecospat` package should be removed (I added the code of `ecospat.boyce` and `ecospat.mpa` functions directly into the package to get rid of the dependency).
Please tell me if you manage to make the `BIOMOD_PresenceOnly` function work once you've reinstalled the `biomod2` package :pray: 

Maya

**Comment by pabloriul** [comment]
Hi Maya,

Great news! Everything worked perfectly. Thank you very much!

Cheers,

Pablo
